/**
 * AcknowledgeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcknowledgeRepository Port
 *
 * DDD: Application port for acknowledgerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcknowledgeTamperEventInput, AcknowledgeTamperEventOutput } from "../dto/acknowledge.dto";
export interface AcknowledgeRepository {
  acknowledgeTamperEvent(input: AcknowledgeTamperEventInput): Promise<AcknowledgeTamperEventOutput>;
}

export type { AcknowledgeTamperEventInput, AcknowledgeTamperEventOutput } from "../dto/acknowledge.dto";
