/**
 * TamperEventRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TamperEventRepository Port
 *
 * DDD: Application port for tampereventrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTamperEventInput, GetTamperEventOutput, ListTamperEventsInput, ListTamperEventsOutput } from "../dto/tamper-event.dto";
export interface TamperEventRepository {
  listTamperEvents(input: ListTamperEventsInput): Promise<ListTamperEventsOutput>;
  getTamperEvent(input: GetTamperEventInput): Promise<GetTamperEventOutput>;
}

export type { GetTamperEventInput, GetTamperEventOutput, ListTamperEventsInput, ListTamperEventsOutput } from "../dto/tamper-event.dto";
