/**
 * VerificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerificationRepository Port
 *
 * DDD: Application port for verificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetVerificationInput, GetVerificationOutput, ListVerificationsInput, ListVerificationsOutput, VerifyLearningBlockInput, VerifyLearningBlockOutput } from "../dto/verification.dto";
export interface VerificationRepository {
  listVerifications(input: ListVerificationsInput): Promise<ListVerificationsOutput>;
  verifyLearningBlock(input: VerifyLearningBlockInput): Promise<VerifyLearningBlockOutput>;
  getVerification(input: GetVerificationInput): Promise<GetVerificationOutput>;
}

export type { GetVerificationInput, GetVerificationOutput, ListVerificationsInput, ListVerificationsOutput, VerifyLearningBlockInput, VerifyLearningBlockOutput } from "../dto/verification.dto";
