/**
 * GetTamperEvent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTamperEvent } from "@veritrace/api-server/domains/verifications/handlers";
import type { VerificationsDDDDependencies } from "@veritrace/api-server/domains/verifications";
import { createTamperEvent as createTamperEventEntity } from "@veritrace/factories/verifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { VERIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTamperEvent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VerificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VerificationsDDDDependencies>(
      VERIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTamperEventEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTamperEvent, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { tamperEventId: entity.id };

    await getTamperEvent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTamperEvent.execute).toHaveBeenCalledWith(expect.objectContaining({ tamperEventId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { tamperEventId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTamperEvent, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTamperEvent(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
