/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Spaces Domain Use Cases
 * 
 * List of all use case names for the spaces domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SPACES_USE_CASES = [
  "executeGetDpiAEvidencePack",
  "executeGetLearningSpace",
  "executeGetNecessityDecision",
  "executeListLearningSpaces",
  "executeListNecessityDecisions",
  "executeRecordNecessityDecision",
  "executeRegisterLearningSpace"
] as const;
