/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAdaptersDomainModule,
  buildBlocksDomainModule,
  buildCommitmentsDomainModule,
  buildConsentsDomainModule,
  buildExportsDomainModule,
  buildIdentityDomainModule,
  buildSpacesDomainModule,
  buildVerificationsDomainModule,
} from "../domains/index.js";
import type {
  AdaptersDomainModule,
  BlocksDomainModule,
  CommitmentsDomainModule,
  ConsentsDomainModule,
  ExportsDomainModule,
  IdentityDomainModule,
  SpacesDomainModule,
  VerificationsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private adaptersModule: AdaptersDomainModule | null = null;
  private blocksModule: BlocksDomainModule | null = null;
  private commitmentsModule: CommitmentsDomainModule | null = null;
  private consentsModule: ConsentsDomainModule | null = null;
  private exportsModule: ExportsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private spacesModule: SpacesDomainModule | null = null;
  private verificationsModule: VerificationsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get adapters domain module
   */
  getAdaptersDependencies(): AdaptersDomainModule {
    if (!this.adaptersModule) {
      this.adaptersModule = buildAdaptersDomainModule(this.dynamoClient);
    }
    return this.adaptersModule;
  }

  /**
   * Get blocks domain module
   */
  getBlocksDependencies(): BlocksDomainModule {
    if (!this.blocksModule) {
      this.blocksModule = buildBlocksDomainModule(this.dynamoClient);
    }
    return this.blocksModule;
  }

  /**
   * Get commitments domain module
   */
  getCommitmentsDependencies(): CommitmentsDomainModule {
    if (!this.commitmentsModule) {
      this.commitmentsModule = buildCommitmentsDomainModule(this.dynamoClient);
    }
    return this.commitmentsModule;
  }

  /**
   * Get consents domain module
   */
  getConsentsDependencies(): ConsentsDomainModule {
    if (!this.consentsModule) {
      this.consentsModule = buildConsentsDomainModule(this.dynamoClient);
    }
    return this.consentsModule;
  }

  /**
   * Get exports domain module
   */
  getExportsDependencies(): ExportsDomainModule {
    if (!this.exportsModule) {
      this.exportsModule = buildExportsDomainModule(this.dynamoClient);
    }
    return this.exportsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get spaces domain module
   */
  getSpacesDependencies(): SpacesDomainModule {
    if (!this.spacesModule) {
      this.spacesModule = buildSpacesDomainModule(this.dynamoClient);
    }
    return this.spacesModule;
  }

  /**
   * Get verifications domain module
   */
  getVerificationsDependencies(): VerificationsDomainModule {
    if (!this.verificationsModule) {
      this.verificationsModule = buildVerificationsDomainModule(this.dynamoClient);
    }
    return this.verificationsModule;
  }

  clearAdaptersDependencies(): void { this.adaptersModule = null; }
  clearBlocksDependencies(): void { this.blocksModule = null; }
  clearCommitmentsDependencies(): void { this.commitmentsModule = null; }
  clearConsentsDependencies(): void { this.consentsModule = null; }
  clearExportsDependencies(): void { this.exportsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearSpacesDependencies(): void { this.spacesModule = null; }
  clearVerificationsDependencies(): void { this.verificationsModule = null; }

  getAdaptersDependenciesForRequest(): AdaptersDomainModule {
    return this.getAdaptersDependencies();
  }

  getBlocksDependenciesForRequest(): BlocksDomainModule {
    return this.getBlocksDependencies();
  }

  getCommitmentsDependenciesForRequest(): CommitmentsDomainModule {
    return this.getCommitmentsDependencies();
  }

  getConsentsDependenciesForRequest(): ConsentsDomainModule {
    return this.getConsentsDependencies();
  }

  getExportsDependenciesForRequest(): ExportsDomainModule {
    return this.getExportsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getSpacesDependenciesForRequest(): SpacesDomainModule {
    return this.getSpacesDependencies();
  }

  getVerificationsDependenciesForRequest(): VerificationsDomainModule {
    return this.getVerificationsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.adaptersModule = null;
    this.blocksModule = null;
    this.commitmentsModule = null;
    this.consentsModule = null;
    this.exportsModule = null;
    this.identityModule = null;
    this.spacesModule = null;
    this.verificationsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
