/**
 * AcknowledgeTamperEvent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { acknowledgeTamperEvent } from "@veritrace/api-server/domains/verifications/handlers";
import type { VerificationsDDDDependencies } from "@veritrace/api-server/domains/verifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { VERIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("AcknowledgeTamperEvent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VerificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VerificationsDDDDependencies>(
      VERIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAcknowledgeTamperEvent, "execute").mockResolvedValue(useCaseResult);

    await acknowledgeTamperEvent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAcknowledgeTamperEvent.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
