/**
 * GetLearningSpace handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getLearningSpace } from "@veritrace/api-server/domains/spaces/handlers";
import type { SpacesDDDDependencies } from "@veritrace/api-server/domains/spaces";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { SPACES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetLearningSpace", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SpacesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SpacesDDDDependencies>(
      SPACES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetLearningSpace, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { spaceId: entity.id };

    await getLearningSpace(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetLearningSpace.execute).toHaveBeenCalledWith(expect.objectContaining({ spaceId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { spaceId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetLearningSpace, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getLearningSpace(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
