/**
 * ExecuteGetConsent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetConsent Use Case
 *
 * DDD: Application use case for get Consent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetConsentInput, GetConsentOutput } from "../dto/consent.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { ConsentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetConsent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly consent: ConsentRepository
  ) {}

  async execute(input: GetConsentInput): Promise<GetConsentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).consentId) {
      throw new ValidationError("consentId is required");
    }
    const consentId = (input as any).consentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.consent.getConsent({ consentId: consentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${consentId}`);
    }

    return entity as GetConsentOutput;
  }
}
