/**
 * ExecuteCreateAccessRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAccessRequest Use Case
 *
 * DDD: Application use case for create AccessRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAccessRequestInput, CreateAccessRequestOutput } from "../dto/access-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { AccessRequestRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAccessRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly accessRequest: AccessRequestRepository
  ) {}

  async execute(input: CreateAccessRequestInput): Promise<CreateAccessRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: activityIds, blockIds, expiresAt, learnerId, purpose, researcherId, spaceId, studyId, studyTitle
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.expiresAt) {
      throw new ValidationError("expiresAt is required");
    }
    if (!input.purpose) {
      throw new ValidationError("purpose is required");
    }
    if (!input.researcherId) {
      throw new ValidationError("researcherId is required");
    }
    if (!input.learnerId) {
      throw new ValidationError("learnerId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (consents domain)
    const entityId = this.idGenerator.cnsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.accessRequest.createAccessRequest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAccessRequestOutput;
  }
}
