/**
 * ExecuteListConsents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListConsents Use Case
 *
 * DDD: Application use case for list Consent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListConsentsInput, ListConsentsOutput } from "../dto/consent.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { ConsentRepository } from "../ports";

export class ExecuteListConsents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly consent: ConsentRepository
  ) {}

  async execute(input: ListConsentsInput): Promise<ListConsentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.consent.listConsents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListConsentsOutput;
  }
}
