/**
 * ExecuteGetAccessRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAccessRequest Use Case
 *
 * DDD: Application use case for get AccessRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAccessRequestInput, GetAccessRequestOutput } from "../dto/access-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { AccessRequestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAccessRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly accessRequest: AccessRequestRepository
  ) {}

  async execute(input: GetAccessRequestInput): Promise<GetAccessRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).accessRequestId) {
      throw new ValidationError("accessRequestId is required");
    }
    const accessrequestId = (input as any).accessRequestId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.accessRequest.getAccessRequest({ accessRequestId: accessrequestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${accessrequestId}`);
    }

    return entity as GetAccessRequestOutput;
  }
}
