/**
 * Routes for Block
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { emitLearningBlock, getLearningBlockMeta, listLearningBlocks } from "../handlers/block.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function blockRoutes(fastify: FastifyInstance) {
  // POST /v1/blocks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/blocks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await emitLearningBlock(request, reply, deps);
      });
    }
  );


  // GET /v1/blocks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/blocks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await listLearningBlocks(request, reply, deps);
      });
    }
  );


  // GET /v1/blocks/{blockId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/blocks/:blockId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { blockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await getLearningBlockMeta(request, reply, deps);
      });
    }
  );


}
