/**
 * Routes for DeletionRequest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDeletionRequest, getDeletionRequest, listDeletionRequests } from "../handlers/deletion-request.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function deletionRequestRoutes(fastify: FastifyInstance) {
  // GET /v1/deletion-requests (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/deletion-requests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await listDeletionRequests(request, reply, deps);
      });
    }
  );


  // POST /v1/blocks/{blockId}/deletion-requests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/blocks/:blockId/deletion-requests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { blockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await createDeletionRequest(request, reply, deps);
      });
    }
  );


  // GET /v1/deletion-requests/{deletionRequestId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/deletion-requests/:deletionRequestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deletionRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlocksDependenciesForRequest();
        await getDeletionRequest(request, reply, deps);
      });
    }
  );


}
