/**
 * Handlers for LbrEndpoint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdaptersDomainModule } from "../dependencies/adapters-ddd.dependencies.js";
import type { CreateLbrEndpointInput, GetLbrEndpointInput, ListLbrEndpointsInput, UpdateLbrEndpointInput } from "@veritrace/services/adapters";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/lbr-endpoints
 * Operation: listLbrEndpoints
 */
export async function listLbrEndpoints(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLbrEndpointsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.lbrEndpoints.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/lbr-endpoints
 * Operation: createLbrEndpoint
 */
export async function createLbrEndpoint(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLbrEndpointInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.lbrEndpoints.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/lbr-endpoints/{lbrEndpointId}
 * Operation: getLbrEndpoint
 */
export async function getLbrEndpoint(
  request: FastifyRequest<{ Params: { lbrEndpointId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLbrEndpointInput = {
    lbrEndpointId: request.params.lbrEndpointId,
  };
  const result = await deps.useCases.lbrEndpoints.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/lbr-endpoints/{lbrEndpointId}
 * Operation: updateLbrEndpoint
 */
export async function updateLbrEndpoint(
  request: FastifyRequest<{ Params: { lbrEndpointId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateLbrEndpointInput = {
    lbrEndpointId: request.params.lbrEndpointId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.lbrEndpoints.update.execute(input);
  return reply.code(200).send(result);
}


