/**
 * Handlers for LbrLinkage
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdaptersDomainModule } from "../dependencies/adapters-ddd.dependencies.js";
import type { GetLearnerLbrLinkageInput, SetLearnerLbrLinkageInput } from "@veritrace/services/adapters";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/learners/{learnerId}/lbr-linkage
 * Operation: getLearnerLbrLinkage
 */
export async function getLearnerLbrLinkage(
  request: FastifyRequest<{ Params: { learnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLearnerLbrLinkageInput = {
    learnerId: request.params.learnerId,
  };
  const result = await deps.useCases.lbrLinkages.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/learners/{learnerId}/lbr-linkage
 * Operation: setLearnerLbrLinkage
 */
export async function setLearnerLbrLinkage(
  request: FastifyRequest<{ Params: { learnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SetLearnerLbrLinkageInput = {
    learnerId: request.params.learnerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.lbrLinkages.update.execute(input);
  return reply.code(201).send(result);
}


