/**
 * Handlers for LedgerAdapter
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdaptersDomainModule } from "../dependencies/adapters-ddd.dependencies.js";
import type { CreateLedgerAdapterInput, GetLedgerAdapterInput, ListLedgerAdaptersInput } from "@veritrace/services/adapters";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/ledger-adapters
 * Operation: listLedgerAdapters
 */
export async function listLedgerAdapters(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLedgerAdaptersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.ledgerAdapters.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/ledger-adapters
 * Operation: createLedgerAdapter
 */
export async function createLedgerAdapter(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLedgerAdapterInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.ledgerAdapters.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/ledger-adapters/{ledgerAdapterId}
 * Operation: getLedgerAdapter
 */
export async function getLedgerAdapter(
  request: FastifyRequest<{ Params: { ledgerAdapterId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLedgerAdapterInput = {
    ledgerAdapterId: request.params.ledgerAdapterId,
  };
  const result = await deps.useCases.ledgerAdapters.get.execute(input);
  return reply.code(200).send(result);
}


