/**
 * TamperEvent DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TamperEvent DTOs
 *
 * DDD: Application DTOs for TamperEvent use cases.
 */

import type { GetTamperEventParams, ListTamperEventsParams } from "@veritrace/core/verifications/types";

export type ListTamperEventsInput = ListTamperEventsParams;

export type GetTamperEventInput = GetTamperEventParams;

export type ListTamperEventsOutput = {};

export type GetTamperEventOutput = {};
