/**
 * Verification DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Verification DTOs
 *
 * DDD: Application DTOs for Verification use cases.
 */

import type { GetVerificationParams, ListVerificationsParams, VerifyLearningBlockRequestInput } from "@veritrace/core/verifications/types";

export type ListVerificationsInput = ListVerificationsParams;

export type VerifyLearningBlockInput = VerifyLearningBlockRequestInput;

export type GetVerificationInput = GetVerificationParams;

export type ListVerificationsOutput = {};

export type VerifyLearningBlockOutput = {};

export type GetVerificationOutput = {};
