/**
 * ExecuteListLearningSpaces - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLearningSpaces Use Case
 *
 * DDD: Application use case for list Space.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLearningSpacesInput, ListLearningSpacesOutput } from "../dto/space.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { SpaceRepository } from "../ports";

export class ExecuteListLearningSpaces {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly space: SpaceRepository
  ) {}

  async execute(input: ListLearningSpacesInput): Promise<ListLearningSpacesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.spcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.space.listLearningSpaces({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLearningSpacesOutput;
  }
}
