/**
 * ExecuteGetLearningSpace - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetLearningSpace Use Case
 *
 * DDD: Application use case for get Space.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetLearningSpaceInput, GetLearningSpaceOutput } from "../dto/space.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { SpaceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetLearningSpace {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly space: SpaceRepository
  ) {}

  async execute(input: GetLearningSpaceInput): Promise<GetLearningSpaceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.spcId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).spaceId) {
      throw new ValidationError("spaceId is required");
    }
    const spaceId = (input as any).spaceId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.space.getLearningSpace({ spaceId: spaceId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${spaceId}`);
    }

    return entity as GetLearningSpaceOutput;
  }
}
