/**
 * ExecuteListNecessityDecisions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListNecessityDecisions Use Case
 *
 * DDD: Application use case for list NecessityDecision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListNecessityDecisionsInput, ListNecessityDecisionsOutput } from "../dto/necessity-decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { NecessityDecisionRepository } from "../ports";

export class ExecuteListNecessityDecisions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly necessityDecision: NecessityDecisionRepository
  ) {}

  async execute(input: ListNecessityDecisionsInput): Promise<ListNecessityDecisionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.spcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.necessityDecision.listNecessityDecisions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListNecessityDecisionsOutput;
  }
}
