/**
 * Verifications DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Verifications Domain Module - Composition root
 *
 * DDD: Composition root for verifications domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  TamperEventRepositoryAdapter,
  VerificationRepositoryAdapter,
} from "@veritrace/adapters/verifications";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeTamperEvent,
  ExecuteGetTamperEvent,
  ExecuteGetVerification,
  ExecuteListTamperEvents,
  ExecuteListVerifications,
  ExecuteVerifyLearningBlock,
} from "@veritrace/services/verifications/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  TamperEventRepository,
  VerificationRepository,
} from "@veritrace/services/verifications/ports";

export interface VerificationsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    tamperEvents: TamperEventRepository;
    verifications: VerificationRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeTamperEvent;
    };
    tamperEvents: {
      get: ExecuteGetTamperEvent;
      list: ExecuteListTamperEvents;
    };
    verifications: {
      get: ExecuteGetVerification;
      list: ExecuteListVerifications;
    };
  };
}

export function buildVerificationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): VerificationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      tamperEvents?: TamperEventRepository;
      verifications?: VerificationRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.tamperEvents = new TamperEventRepositoryAdapter(dynamoClient);
    obj.verifications = new VerificationRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      tamperEvents: obj.tamperEvents!,
      verifications: obj.verifications!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeTamperEvent(executionContext, idGenerator, repos.acknowledges),
    },
    tamperEvents: {
      get: new ExecuteGetTamperEvent(executionContext, idGenerator, repos.tamperEvents),
      list: new ExecuteListTamperEvents(executionContext, idGenerator, repos.tamperEvents),
    },
    verifications: {
      get: new ExecuteGetVerification(executionContext, idGenerator, repos.verifications),
      list: new ExecuteListVerifications(executionContext, idGenerator, repos.verifications),
    },
  };
  return { repos, useCases: useCases as VerificationsDomainModule["useCases"] };
}
