/**
 * Handlers for DeletionRequest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BlocksDomainModule } from "../dependencies/blocks-ddd.dependencies.js";
import type { CreateDeletionRequestInput, GetDeletionRequestInput, ListDeletionRequestsInput } from "@veritrace/services/blocks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/blocks/{blockId}/deletion-requests
 * Operation: createDeletionRequest
 */
export async function createDeletionRequest(
  request: FastifyRequest<{ Params: { blockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BlocksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDeletionRequestInput = {
    blockId: request.params.blockId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.deletionRequests.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/deletion-requests
 * Operation: listDeletionRequests
 */
export async function listDeletionRequests(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], learnerId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BlocksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDeletionRequestsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.deletionRequests.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/deletion-requests/{deletionRequestId}
 * Operation: getDeletionRequest
 */
export async function getDeletionRequest(
  request: FastifyRequest<{ Params: { deletionRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BlocksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDeletionRequestInput = {
    deletionRequestId: request.params.deletionRequestId,
  };
  const result = await deps.useCases.deletionRequests.get.execute(input);
  return reply.code(200).send(result);
}


