/**
 * CreateDeletionRequest handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createDeletionRequest } from "@veritrace/api-server/domains/blocks/handlers";
import type { BlocksDDDDependencies } from "@veritrace/api-server/domains/blocks";
import { createDeletionRequest as createDeletionRequestEntity } from "@veritrace/factories/blocks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { BLOCKS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateDeletionRequest", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BlocksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BlocksDDDDependencies>(
      BLOCKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDeletionRequestEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateDeletionRequest, "execute").mockResolvedValue(useCaseResult);

    await createDeletionRequest(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateDeletionRequest.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
