/**
 * DeletionRequest Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DeletionRequestEntity } from "@veritrace/core/blocks/models/index.js";
import { blocksSchemas } from "@veritrace/core/blocks";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "blk";

export function createDeletionRequest(overrides: Partial<DeletionRequestEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    blockId: overrides.blockId ?? `blk_${ulid().toLowerCase()}`,
    deletionRequestId: overrides.deletionRequestId ?? `del_${ulid().toLowerCase()}`,
    learnerId: overrides.learnerId ?? `lrn_${ulid().toLowerCase()}`,
    requestedAt: overrides.requestedAt ?? new Date().toISOString(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return blocksSchemas.DeletionRequest.parse(raw);
}

export function deletionRequestBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDeletionRequest(overrides));
}
