/**
 * AccessRequest Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AccessRequestEntity } from "@veritrace/core/consents/models/index.js";
import { consentsSchemas } from "@veritrace/core/consents";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cns";

export function createAccessRequest(overrides: Partial<AccessRequestEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    accessRequestId: overrides.accessRequestId ?? `acr_${ulid().toLowerCase()}`,
    expiresAt: overrides.expiresAt ?? new Date().toISOString(),
    learnerId: overrides.learnerId ?? `lrn_${ulid().toLowerCase()}`,
    purpose: overrides.purpose ?? faker.lorem.word(),
    researcherId: overrides.researcherId ?? `usr_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return consentsSchemas.AccessRequest.parse(raw);
}

export function accessRequestBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAccessRequest(overrides));
}
