/**
 * AccessRequest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccessRequest DTOs
 *
 * DDD: Application DTOs for AccessRequest use cases.
 */

import type { CreateAccessRequestRequestInput, GetAccessRequestParams, ListAccessRequestsParams } from "@veritrace/core/consents/types";

export type ListAccessRequestsInput = ListAccessRequestsParams;

export type CreateAccessRequestInput = CreateAccessRequestRequestInput;

export type GetAccessRequestInput = GetAccessRequestParams;

export type ListAccessRequestsOutput = {};

export type CreateAccessRequestOutput = {};

export type GetAccessRequestOutput = {};
