/**
 * Consent DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Consent DTOs
 *
 * DDD: Application DTOs for Consent use cases.
 */

import type { CreateConsentGrantRequestInput, GetConsentParams, ListConsentsParams } from "@veritrace/core/consents/types";

export type ListConsentsInput = ListConsentsParams;

export type CreateConsentGrantInput = CreateConsentGrantRequestInput;

export type GetConsentInput = GetConsentParams;

export type ListConsentsOutput = {};

export type CreateConsentGrantOutput = {};

export type GetConsentOutput = {};
