/**
 * Revoke DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Revoke DTOs
 *
 * DDD: Application DTOs for Revoke use cases.
 */

import type { RevokeConsentParams } from "@veritrace/core/consents/types";

export type RevokeConsentInput = RevokeConsentParams;

export type RevokeConsentOutput = {};
