/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./acknowledge-repository.ddb.js";
export * from "./tamper-event-repository.ddb.js";
export * from "./verification-repository.ddb.js";
export * from "./acknowledge-repository.adapter.js";
export * from "./tamper-event-repository.adapter.js";
export * from "./verification-repository.adapter.js";
