/**
 * TamperEventRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TamperEventRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TamperEventRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TamperEventRepository,
} from "@veritrace/services/verifications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TamperEventRepositoryDdb } from "./tamper-event-repository.ddb.js";

/**
 * TamperEventRepositoryAdapter
 *
 * Implements TamperEventRepository port for infrastructure layer.
 */
export class TamperEventRepositoryAdapter implements TamperEventRepository {
  private readonly ddb: TamperEventRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TamperEventRepositoryDdb(this.dynamoClient);
  }

  async listTamperEvents(input: Parameters<TamperEventRepository['listTamperEvents']>[0]): Promise<Awaited<ReturnType<TamperEventRepository['listTamperEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTamperEvents(input);
  }

  async getTamperEvent(input: Parameters<TamperEventRepository['getTamperEvent']>[0]): Promise<Awaited<ReturnType<TamperEventRepository['getTamperEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTamperEvent(input);
  }
}
