/**
 * VerificationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerificationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VerificationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VerificationRepository,
} from "@veritrace/services/verifications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VerificationRepositoryDdb } from "./verification-repository.ddb.js";

/**
 * VerificationRepositoryAdapter
 *
 * Implements VerificationRepository port for infrastructure layer.
 */
export class VerificationRepositoryAdapter implements VerificationRepository {
  private readonly ddb: VerificationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VerificationRepositoryDdb(this.dynamoClient);
  }

  async listVerifications(input: Parameters<VerificationRepository['listVerifications']>[0]): Promise<Awaited<ReturnType<VerificationRepository['listVerifications']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVerifications(input);
  }

  async verifyLearningBlock(input: Parameters<VerificationRepository['verifyLearningBlock']>[0]): Promise<Awaited<ReturnType<VerificationRepository['verifyLearningBlock']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.verifyLearningBlock(input);
  }

  async getVerification(input: Parameters<VerificationRepository['getVerification']>[0]): Promise<Awaited<ReturnType<VerificationRepository['getVerification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getVerification(input);
  }
}
