/**
 * ExecuteListTamperEvents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTamperEvents Use Case
 *
 * DDD: Application use case for list TamperEvent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTamperEventsInput, ListTamperEventsOutput } from "../dto/tamper-event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { TamperEventRepository } from "../ports";

export class ExecuteListTamperEvents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tamperEvent: TamperEventRepository
  ) {}

  async execute(input: ListTamperEventsInput): Promise<ListTamperEventsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vrfId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.tamperEvent.listTamperEvents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTamperEventsOutput;
  }
}
