/**
 * ExecuteGetTamperEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTamperEvent Use Case
 *
 * DDD: Application use case for get TamperEvent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTamperEventInput, GetTamperEventOutput } from "../dto/tamper-event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { TamperEventRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetTamperEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tamperEvent: TamperEventRepository
  ) {}

  async execute(input: GetTamperEventInput): Promise<GetTamperEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vrfId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).tamperEventId) {
      throw new ValidationError("tamperEventId is required");
    }
    const tampereventId = (input as any).tamperEventId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.tamperEvent.getTamperEvent({ tamperEventId: tampereventId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${tampereventId}`);
    }

    return entity as GetTamperEventOutput;
  }
}
