/**
 * ExecuteVerifyLearningBlock - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteVerifyLearningBlock Use Case
 *
 * DDD: Application use case for get Verification.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { VerifyLearningBlockInput, VerifyLearningBlockOutput } from "../dto/verification.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { VerificationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteVerifyLearningBlock {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly verification: VerificationRepository
  ) {}

  async execute(input: VerifyLearningBlockInput): Promise<VerifyLearningBlockOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vrfId();

    // All field names extracted from OpenAPI spec: allowNoAnchor, blockId, consentId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).blockId) {
      throw new ValidationError("blockId is required");
    }
    const blockId = (input as any).blockId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.verification.verifyLearningBlock({ blockId: blockId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${blockId}`);
    }

    return entity as VerifyLearningBlockOutput;
  }
}
