/**
 * Consents Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createConsentGrant_Body = z
  .object({
    learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
    researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
    accessRequestId: z
      .string()
      .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    spaceId: z
      .string()
      .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    purpose: z.string().min(1).max(2000),
    studyId: z.string().max(100).optional(),
    expiresAt: z.string().datetime({ offset: true }),
    blockIds: z.array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/)).min(1),
    guardianApproved: z.boolean().optional().default(false),
  })
  .passthrough();
const createAccessRequest_Body = z
  .object({
    learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
    researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
    spaceId: z
      .string()
      .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    purpose: z.string().min(1).max(2000),
    studyId: z.string().max(100).optional(),
    studyTitle: z.string().max(300).optional(),
    expiresAt: z.string().datetime({ offset: true }),
    activityIds: z
      .array(z.string().regex(/^act_[0-9A-HJKMNP-TV-Z]{26}$/))
      .optional(),
    blockIds: z
      .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
      .optional(),
  })
  .passthrough();
const decideAccessRequest_Body = z
  .object({
    decision: z.enum(['approve', 'deny']),
    rationale: z.string().max(2000).optional(),
    expiresAt: z.string().datetime({ offset: true }).optional(),
    blockIds: z
      .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
      .optional(),
    guardianApproved: z.boolean().optional().default(false),
  })
  .passthrough();

export const schemas: any = {
  createConsentGrant_Body,
  createAccessRequest_Body,
  decideAccessRequest_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/access-requests',
    alias: 'listAccessRequests',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'learnerId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'researcherId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['pending', 'granted', 'denied', 'expired']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  accessRequestId: z
                    .string()
                    .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
                  researcherId: z
                    .string()
                    .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  spaceId: z
                    .string()
                    .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  purpose: z.string().min(1).max(2000),
                  studyId: z.string().max(100).optional(),
                  studyTitle: z.string().max(300).optional(),
                  expiresAt: z.string().datetime({ offset: true }),
                  activityIds: z
                    .array(z.string().regex(/^act_[0-9A-HJKMNP-TV-Z]{26}$/))
                    .optional(),
                  blockIds: z
                    .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
                    .optional(),
                  status: z.enum(['pending', 'granted', 'denied', 'expired']),
                  decisionRationale: z.string().max(2000).optional(),
                  resultingConsentId: z
                    .string()
                    .regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  decidedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/access-requests',
    alias: 'createAccessRequest',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createAccessRequest_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            accessRequestId: z.string().regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            studyTitle: z.string().max(300).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            activityIds: z
              .array(z.string().regex(/^act_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            status: z.enum(['pending', 'granted', 'denied', 'expired']),
            decisionRationale: z.string().max(2000).optional(),
            resultingConsentId: z
              .string()
              .regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/access-requests/:accessRequestId',
    alias: 'getAccessRequest',
    requestFormat: 'json',
    parameters: [
      {
        name: 'accessRequestId',
        type: 'Path',
        schema: z.string().regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            accessRequestId: z.string().regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            studyTitle: z.string().max(300).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            activityIds: z
              .array(z.string().regex(/^act_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            status: z.enum(['pending', 'granted', 'denied', 'expired']),
            decisionRationale: z.string().max(2000).optional(),
            resultingConsentId: z
              .string()
              .regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/access-requests/:accessRequestId/decide',
    alias: 'decideAccessRequest',
    description: `Learner (or guardian) decision. Approve may mint a ConsentGrant; deny is terminal
(no silent retry loop in product UX).
`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: decideAccessRequest_Body,
      },
      {
        name: 'accessRequestId',
        type: 'Path',
        schema: z.string().regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            accessRequestId: z.string().regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            studyTitle: z.string().max(300).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            activityIds: z
              .array(z.string().regex(/^act_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .optional(),
            status: z.enum(['pending', 'granted', 'denied', 'expired']),
            decisionRationale: z.string().max(2000).optional(),
            resultingConsentId: z
              .string()
              .regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            decidedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/consents',
    alias: 'listConsents',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'learnerId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'researcherId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['active', 'revoked', 'expired']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  consentId: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
                  learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
                  researcherId: z
                    .string()
                    .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  accessRequestId: z
                    .string()
                    .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  spaceId: z
                    .string()
                    .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  purpose: z.string().min(1).max(2000),
                  studyId: z.string().max(100).optional(),
                  expiresAt: z.string().datetime({ offset: true }),
                  status: z.enum(['active', 'revoked', 'expired']),
                  blockIds: z
                    .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
                    .min(1),
                  guardianApproved: z.boolean().optional(),
                  revokedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/consents',
    alias: 'createConsentGrant',
    description: `Learner (or guardian) grants purpose-limited, time-boxed access to selected blocks.`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createConsentGrant_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            consentId: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            accessRequestId: z
              .string()
              .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            status: z.enum(['active', 'revoked', 'expired']),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .min(1),
            guardianApproved: z.boolean().optional(),
            revokedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/consents/:consentId',
    alias: 'getConsent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'consentId',
        type: 'Path',
        schema: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            consentId: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            accessRequestId: z
              .string()
              .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            status: z.enum(['active', 'revoked', 'expired']),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .min(1),
            guardianApproved: z.boolean().optional(),
            revokedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/consents/:consentId/revoke',
    alias: 'revokeConsent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'consentId',
        type: 'Path',
        schema: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            consentId: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            learnerId: z.string().regex(/^lrn_[0-9A-HJKMNP-TV-Z]{26}$/),
            researcherId: z.string().regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/),
            accessRequestId: z
              .string()
              .regex(/^acr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            spaceId: z
              .string()
              .regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            purpose: z.string().min(1).max(2000),
            studyId: z.string().max(100).optional(),
            expiresAt: z.string().datetime({ offset: true }),
            status: z.enum(['active', 'revoked', 'expired']),
            blockIds: z
              .array(z.string().regex(/^blk_[0-9A-HJKMNP-TV-Z]{26}$/))
              .min(1),
            guardianApproved: z.boolean().optional(),
            revokedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
