/**
 * Spaces DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Spaces Domain Module - Composition root
 *
 * DDD: Composition root for spaces domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DpiaEvidenceRepositoryAdapter,
  NecessityDecisionRepositoryAdapter,
  SpaceRepositoryAdapter,
} from "@veritrace/adapters/spaces";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDpiAEvidencePack,
  ExecuteGetLearningSpace,
  ExecuteGetNecessityDecision,
  ExecuteListLearningSpaces,
  ExecuteListNecessityDecisions,
  ExecuteRecordNecessityDecision,
  ExecuteRegisterLearningSpace,
} from "@veritrace/services/spaces/usecases";
// Ports (interfaces)
import type {
  DpiaEvidenceRepository,
  NecessityDecisionRepository,
  SpaceRepository,
} from "@veritrace/services/spaces/ports";

export interface SpacesDomainModule {
  repos: {
    dpiaEvidences: DpiaEvidenceRepository;
    necessityDecisions: NecessityDecisionRepository;
    spaces: SpaceRepository;
  };
  useCases: {
    dpiaEvidences: {
      get: ExecuteGetDpiAEvidencePack;
    };
    necessityDecisions: {
      get: ExecuteGetNecessityDecision;
      list: ExecuteListNecessityDecisions;
    };
    spaces: {
      create: ExecuteRegisterLearningSpace;
      get: ExecuteGetLearningSpace;
      list: ExecuteListLearningSpaces;
    };
  };
}

export function buildSpacesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SpacesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dpiaEvidences?: DpiaEvidenceRepository;
      necessityDecisions?: NecessityDecisionRepository;
      spaces?: SpaceRepository;
    } = {};

    obj.dpiaEvidences = new DpiaEvidenceRepositoryAdapter(dynamoClient);
    obj.necessityDecisions = new NecessityDecisionRepositoryAdapter(dynamoClient);
    obj.spaces = new SpaceRepositoryAdapter(dynamoClient);
    return {
      dpiaEvidences: obj.dpiaEvidences!,
      necessityDecisions: obj.necessityDecisions!,
      spaces: obj.spaces!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dpiaEvidences: {
      get: new ExecuteGetDpiAEvidencePack(executionContext, idGenerator, repos.dpiaEvidences),
    },
    necessityDecisions: {
      get: new ExecuteGetNecessityDecision(executionContext, idGenerator, repos.necessityDecisions),
      list: new ExecuteListNecessityDecisions(executionContext, idGenerator, repos.necessityDecisions),
    },
    spaces: {
      create: new ExecuteRegisterLearningSpace(executionContext, idGenerator, repos.spaces),
      get: new ExecuteGetLearningSpace(executionContext, idGenerator, repos.spaces),
      list: new ExecuteListLearningSpaces(executionContext, idGenerator, repos.spaces),
    },
  };
  return { repos, useCases: useCases as SpacesDomainModule["useCases"] };
}
