/**
 * Routes for LbrEndpoint
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createLbrEndpoint, getLbrEndpoint, listLbrEndpoints, updateLbrEndpoint } from "../handlers/lbr-endpoint.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function lbrEndpointRoutes(fastify: FastifyInstance) {
  // POST /v1/lbr-endpoints (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/lbr-endpoints",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await createLbrEndpoint(request, reply, deps);
      });
    }
  );


  // GET /v1/lbr-endpoints (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/lbr-endpoints",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await listLbrEndpoints(request, reply, deps);
      });
    }
  );


  // GET /v1/lbr-endpoints/{lbrEndpointId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/lbr-endpoints/:lbrEndpointId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { lbrEndpointId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await getLbrEndpoint(request, reply, deps);
      });
    }
  );


  // PATCH /v1/lbr-endpoints/{lbrEndpointId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/lbr-endpoints/:lbrEndpointId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { lbrEndpointId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await updateLbrEndpoint(request, reply, deps);
      });
    }
  );


}
