/**
 * Routes for LbrLinkage
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLearnerLbrLinkage, setLearnerLbrLinkage } from "../handlers/lbr-linkage.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function lbrLinkageRoutes(fastify: FastifyInstance) {
  // GET /v1/learners/{learnerId}/lbr-linkage (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/learners/:learnerId/lbr-linkage",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { learnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await getLearnerLbrLinkage(request, reply, deps);
      });
    }
  );


  // POST /v1/learners/{learnerId}/lbr-linkage (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/learners/:learnerId/lbr-linkage",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { learnerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await setLearnerLbrLinkage(request, reply, deps);
      });
    }
  );


}
