/**
 * Routes for LedgerAdapter
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createLedgerAdapter, getLedgerAdapter, listLedgerAdapters } from "../handlers/ledger-adapter.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ledgerAdapterRoutes(fastify: FastifyInstance) {
  // POST /v1/ledger-adapters (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/ledger-adapters",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await createLedgerAdapter(request, reply, deps);
      });
    }
  );


  // GET /v1/ledger-adapters (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ledger-adapters",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await listLedgerAdapters(request, reply, deps);
      });
    }
  );


  // GET /v1/ledger-adapters/{ledgerAdapterId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ledger-adapters/:ledgerAdapterId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ledgerAdapterId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAdaptersDependenciesForRequest();
        await getLedgerAdapter(request, reply, deps);
      });
    }
  );


}
