/**
 * Handlers for Commitment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CommitmentsDomainModule } from "../dependencies/commitments-ddd.dependencies.js";
import type { AnchorCommitmentInput, GetCommitmentInput, ListCommitmentsInput } from "@veritrace/services/commitments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/commitments
 * Operation: listCommitments
 */
export async function listCommitments(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], blockId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CommitmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCommitmentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.commitments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/commitments
 * Operation: anchorCommitment
 */
export async function anchorCommitment(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CommitmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AnchorCommitmentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.commitments.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/commitments/{commitmentId}
 * Operation: getCommitment
 */
export async function getCommitment(
  request: FastifyRequest<{ Params: { commitmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CommitmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCommitmentInput = {
    commitmentId: request.params.commitmentId,
  };
  const result = await deps.useCases.commitments.get.execute(input);
  return reply.code(200).send(result);
}


