/**
 * DpiaEvidence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DpiaEvidence DTOs
 *
 * DDD: Application DTOs for DpiaEvidence use cases.
 */

import type { GetDpiAEvidencePackParams } from "@veritrace/core/spaces/types";

export type GetDpiAEvidencePackInput = GetDpiAEvidencePackParams;

export type GetDpiAEvidencePackOutput = {};
