/**
 * NecessityDecision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NecessityDecision DTOs
 *
 * DDD: Application DTOs for NecessityDecision use cases.
 */

import type { GetNecessityDecisionParams, ListNecessityDecisionsParams, RecordNecessityDecisionParams, RecordNecessityDecisionRequestInput } from "@veritrace/core/spaces/types";

export type ListNecessityDecisionsInput = ListNecessityDecisionsParams;

export type RecordNecessityDecisionInput = RecordNecessityDecisionParams & RecordNecessityDecisionRequestInput;

export type GetNecessityDecisionInput = GetNecessityDecisionParams;

export type ListNecessityDecisionsOutput = {};

export type RecordNecessityDecisionOutput = {};

export type GetNecessityDecisionOutput = {};
