/**
 * Space DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Space DTOs
 *
 * DDD: Application DTOs for Space use cases.
 */

import type { GetLearningSpaceParams, ListLearningSpacesParams, RegisterLearningSpaceRequestInput } from "@veritrace/core/spaces/types";

export type ListLearningSpacesInput = ListLearningSpacesParams;

export type RegisterLearningSpaceInput = RegisterLearningSpaceRequestInput;

export type GetLearningSpaceInput = GetLearningSpaceParams;

export type ListLearningSpacesOutput = {};

export type RegisterLearningSpaceOutput = {};

export type GetLearningSpaceOutput = {};
