/**
 * DeletionRequest Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/blocks.openapi.types.js";
import { schemas } from "../schemas/blocks.schemas.js";

/**
 * Entity: DeletionRequestEntity
 * Description: Represents the DeletionRequest domain model.
 * Source: schemas.DeletionRequest
 * Type: Domain Entity (API)
 */
export const DeletionRequestEntitySchema = schemas.DeletionRequest;
export type DeletionRequestEntity = components["schemas"]["DeletionRequest"];
