/**
 * Blocks DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Blocks Domain Module - Composition root
 *
 * DDD: Composition root for blocks domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BlockRepositoryAdapter,
  DeletionRequestRepositoryAdapter,
} from "@veritrace/adapters/blocks";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDeletionRequest,
  ExecuteEmitLearningBlock,
  ExecuteGetDeletionRequest,
  ExecuteGetLearningBlockMeta,
  ExecuteListDeletionRequests,
  ExecuteListLearningBlocks,
} from "@veritrace/services/blocks/usecases";
// Ports (interfaces)
import type {
  BlockRepository,
  DeletionRequestRepository,
} from "@veritrace/services/blocks/ports";

export interface BlocksDomainModule {
  repos: {
    blocks: BlockRepository;
    deletionRequests: DeletionRequestRepository;
  };
  useCases: {
    blocks: {
      get: ExecuteGetLearningBlockMeta;
      list: ExecuteListLearningBlocks;
    };
    deletionRequests: {
      create: ExecuteCreateDeletionRequest;
      get: ExecuteGetDeletionRequest;
      list: ExecuteListDeletionRequests;
    };
  };
}

export function buildBlocksDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BlocksDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      blocks?: BlockRepository;
      deletionRequests?: DeletionRequestRepository;
    } = {};

    obj.blocks = new BlockRepositoryAdapter(dynamoClient);
    obj.deletionRequests = new DeletionRequestRepositoryAdapter(dynamoClient);
    return {
      blocks: obj.blocks!,
      deletionRequests: obj.deletionRequests!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    blocks: {
      get: new ExecuteGetLearningBlockMeta(executionContext, idGenerator, repos.blocks),
      list: new ExecuteListLearningBlocks(executionContext, idGenerator, repos.blocks),
    },
    deletionRequests: {
      create: new ExecuteCreateDeletionRequest(executionContext, idGenerator, repos.deletionRequests),
      get: new ExecuteGetDeletionRequest(executionContext, idGenerator, repos.deletionRequests),
      list: new ExecuteListDeletionRequests(executionContext, idGenerator, repos.deletionRequests),
    },
  };
  return { repos, useCases: useCases as BlocksDomainModule["useCases"] };
}
