/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ExportsDomainModule } from "../dependencies/exports-ddd.dependencies.js";
import type { CreateResearchExportInput, GetResearchExportInput, ListResearchExportsInput } from "@veritrace/services/exports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/exports
 * Operation: listResearchExports
 */
export async function listResearchExports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], consentId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListResearchExportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.exports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/exports
 * Operation: createResearchExport
 */
export async function createResearchExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateResearchExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/exports/{exportId}
 * Operation: getResearchExport
 */
export async function getResearchExport(
  request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetResearchExportInput = {
    exportId: request.params.exportId,
  };
  const result = await deps.useCases.exports.get.execute(input);
  return reply.code(200).send(result);
}


