/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Verifications Domain Use Cases
 * 
 * List of all use case names for the verifications domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VERIFICATIONS_USE_CASES = [
  "executeAcknowledgeTamperEvent",
  "executeGetTamperEvent",
  "executeGetVerification",
  "executeListTamperEvents",
  "executeListVerifications",
  "executeVerifyLearningBlock"
] as const;
