/**
 * DecideRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecideRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DecideRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DecideRepository,
} from "@veritrace/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DecideRepositoryDdb } from "./decide-repository.ddb.js";

/**
 * DecideRepositoryAdapter
 *
 * Implements DecideRepository port for infrastructure layer.
 */
export class DecideRepositoryAdapter implements DecideRepository {
  private readonly ddb: DecideRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DecideRepositoryDdb(this.dynamoClient);
  }

  async decideAccessRequest(input: Parameters<DecideRepository['decideAccessRequest']>[0]): Promise<Awaited<ReturnType<DecideRepository['decideAccessRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideAccessRequest(input);
  }
}
