/**
 * AccessRequest Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consents.openapi.types.js";
import { schemas } from "../schemas/consents.schemas.js";

/**
 * Entity: AccessRequestEntity
 * Description: Represents the AccessRequest domain model.
 * Source: schemas.AccessRequest
 * Type: Domain Entity (API)
 */
export const AccessRequestEntitySchema = schemas.AccessRequest;
export type AccessRequestEntity = components["schemas"]["AccessRequest"];
