/**
 * Block DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Block DTOs
 *
 * DDD: Application DTOs for Block use cases.
 */

import type { EmitLearningBlockRequestInput, GetLearningBlockMetaParams, ListLearningBlocksParams } from "@veritrace/core/blocks/types";

export type ListLearningBlocksInput = ListLearningBlocksParams;

export type EmitLearningBlockInput = EmitLearningBlockRequestInput;

export type GetLearningBlockMetaInput = GetLearningBlockMetaParams;

export type ListLearningBlocksOutput = {};

export type EmitLearningBlockOutput = {};

export type GetLearningBlockMetaOutput = {};
