/**
 * DeletionRequest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeletionRequest DTOs
 *
 * DDD: Application DTOs for DeletionRequest use cases.
 */

import type { CreateDeletionRequestParams, CreateDeletionRequestRequestInput, GetDeletionRequestParams, ListDeletionRequestsParams } from "@veritrace/core/blocks/types";

export type CreateDeletionRequestInput = CreateDeletionRequestParams & CreateDeletionRequestRequestInput;

export type ListDeletionRequestsInput = ListDeletionRequestsParams;

export type GetDeletionRequestInput = GetDeletionRequestParams;

export type CreateDeletionRequestOutput = {};

export type ListDeletionRequestsOutput = {};

export type GetDeletionRequestOutput = {};
