/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@veritrace/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "adapters", "blocks", "commitments", "consents", "exports", "identity", "spaces", "verifications"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      adapters: [{ method: "GET", path: "/v1/lbr-endpoints" }, { method: "POST", path: "/v1/lbr-endpoints" }, { method: "GET", path: "/v1/lbr-endpoints/:lbrEndpointId" }, { method: "PATCH", path: "/v1/lbr-endpoints/:lbrEndpointId" }, { method: "GET", path: "/v1/ledger-adapters" }, { method: "POST", path: "/v1/ledger-adapters" }, { method: "GET", path: "/v1/ledger-adapters/:ledgerAdapterId" }, { method: "GET", path: "/v1/learners/:learnerId/lbr-linkage" }, { method: "POST", path: "/v1/learners/:learnerId/lbr-linkage" }],
      blocks: [{ method: "GET", path: "/v1/blocks" }, { method: "POST", path: "/v1/blocks" }, { method: "GET", path: "/v1/blocks/:blockId" }, { method: "POST", path: "/v1/blocks/:blockId/deletion-requests" }, { method: "GET", path: "/v1/deletion-requests" }, { method: "GET", path: "/v1/deletion-requests/:deletionRequestId" }],
      commitments: [{ method: "GET", path: "/v1/commitments" }, { method: "POST", path: "/v1/commitments" }, { method: "GET", path: "/v1/commitments/:commitmentId" }],
      consents: [{ method: "GET", path: "/v1/consents" }, { method: "POST", path: "/v1/consents" }, { method: "GET", path: "/v1/consents/:consentId" }, { method: "POST", path: "/v1/consents/:consentId/revoke" }, { method: "GET", path: "/v1/access-requests" }, { method: "POST", path: "/v1/access-requests" }, { method: "GET", path: "/v1/access-requests/:accessRequestId" }, { method: "POST", path: "/v1/access-requests/:accessRequestId/decide" }],
      exports: [{ method: "GET", path: "/v1/exports" }, { method: "POST", path: "/v1/exports" }, { method: "GET", path: "/v1/exports/:exportId" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      spaces: [{ method: "GET", path: "/v1/spaces" }, { method: "POST", path: "/v1/spaces" }, { method: "GET", path: "/v1/spaces/:spaceId" }, { method: "GET", path: "/v1/spaces/:spaceId/necessity-decisions" }, { method: "POST", path: "/v1/spaces/:spaceId/necessity-decisions" }, { method: "GET", path: "/v1/spaces/:spaceId/necessity-decisions/:necessityDecisionId" }, { method: "GET", path: "/v1/spaces/:spaceId/dpia-evidence" }],
      verifications: [{ method: "GET", path: "/v1/verifications" }, { method: "POST", path: "/v1/verifications" }, { method: "GET", path: "/v1/verifications/:verificationId" }, { method: "GET", path: "/v1/tamper-events" }, { method: "GET", path: "/v1/tamper-events/:tamperEventId" }, { method: "POST", path: "/v1/tamper-events/:tamperEventId/acknowledge" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
