/**
 * GetBlock DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLearningBlockMetaParams } from "@veritrace/core/blocks";

export function createGetBlockRequest(overrides: Partial<GetLearningBlockMetaParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
