/**
 * ListBlock DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListLearningBlocksParams } from "@veritrace/core/blocks";

export function createListBlockRequest(overrides: Partial<ListLearningBlocksParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
