/**
 * Export DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Export DTOs
 *
 * DDD: Application DTOs for Export use cases.
 */

import type { CreateResearchExportRequestInput, GetResearchExportParams, ListResearchExportsParams } from "@veritrace/core/exports/types";

export type ListResearchExportsInput = ListResearchExportsParams;

export type CreateResearchExportInput = CreateResearchExportRequestInput;

export type GetResearchExportInput = GetResearchExportParams;

export type ListResearchExportsOutput = {};

export type CreateResearchExportOutput = {};

export type GetResearchExportOutput = {};
