apis:
  identity:
    root: src/identity.yaml
  spaces:
    root: src/spaces.yaml
  blocks:
    root: src/blocks.yaml
  commitments:
    root: src/commitments.yaml
  consents:
    root: src/consents.yaml
  verifications:
    root: src/verifications.yaml
  exports:
    root: src/exports.yaml
  adapters:
    root: src/adapters.yaml

extends:
  - recommended

rules:
  no-unused-components: off
  operation-4xx-response: warn
  info-license: off
  info-license-url: off
  tag-description: off
  operation-operationId: error
  no-invalid-media-type-examples: off

theme:
  openapi:
    generateCodeSamples:
      languages: []
