/**
 * BlockRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockRepository Port
 *
 * DDD: Application port for blockrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EmitLearningBlockInput, EmitLearningBlockOutput, GetLearningBlockMetaInput, GetLearningBlockMetaOutput, ListLearningBlocksInput, ListLearningBlocksOutput } from "../dto/block.dto";
export interface BlockRepository {
  listLearningBlocks(input: ListLearningBlocksInput): Promise<ListLearningBlocksOutput>;
  emitLearningBlock(input: EmitLearningBlockInput): Promise<EmitLearningBlockOutput>;
  getLearningBlockMeta(input: GetLearningBlockMetaInput): Promise<GetLearningBlockMetaOutput>;
}

export type { EmitLearningBlockInput, EmitLearningBlockOutput, GetLearningBlockMetaInput, GetLearningBlockMetaOutput, ListLearningBlocksInput, ListLearningBlocksOutput } from "../dto/block.dto";
