/**
 * DeletionRequestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeletionRequestRepository Port
 *
 * DDD: Application port for deletionrequestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDeletionRequestInput, CreateDeletionRequestOutput, GetDeletionRequestInput, GetDeletionRequestOutput, ListDeletionRequestsInput, ListDeletionRequestsOutput } from "../dto/deletion-request.dto";
export interface DeletionRequestRepository {
  createDeletionRequest(input: CreateDeletionRequestInput): Promise<CreateDeletionRequestOutput>;
  listDeletionRequests(input: ListDeletionRequestsInput): Promise<ListDeletionRequestsOutput>;
  getDeletionRequest(input: GetDeletionRequestInput): Promise<GetDeletionRequestOutput>;
}

export type { CreateDeletionRequestInput, CreateDeletionRequestOutput, GetDeletionRequestInput, GetDeletionRequestOutput, ListDeletionRequestsInput, ListDeletionRequestsOutput } from "../dto/deletion-request.dto";
