/**
 * CommitmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CommitmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CommitmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CommitmentRepository,
} from "@veritrace/services/commitments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CommitmentRepositoryDdb } from "./commitment-repository.ddb.js";

/**
 * CommitmentRepositoryAdapter
 *
 * Implements CommitmentRepository port for infrastructure layer.
 */
export class CommitmentRepositoryAdapter implements CommitmentRepository {
  private readonly ddb: CommitmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CommitmentRepositoryDdb(this.dynamoClient);
  }

  async listCommitments(input: Parameters<CommitmentRepository['listCommitments']>[0]): Promise<Awaited<ReturnType<CommitmentRepository['listCommitments']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCommitments(input);
  }

  async anchorCommitment(input: Parameters<CommitmentRepository['anchorCommitment']>[0]): Promise<Awaited<ReturnType<CommitmentRepository['anchorCommitment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.anchorCommitment(input);
  }

  async getCommitment(input: Parameters<CommitmentRepository['getCommitment']>[0]): Promise<Awaited<ReturnType<CommitmentRepository['getCommitment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCommitment(input);
  }
}
