/**
 * LbrLinkage DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LbrLinkage DTOs
 *
 * DDD: Application DTOs for LbrLinkage use cases.
 */

import type { GetLearnerLbrLinkageParams, SetLearnerLbrLinkageParams, SetLearnerLbrLinkageRequestInput } from "@veritrace/core/adapters/types";

export type GetLearnerLbrLinkageInput = GetLearnerLbrLinkageParams;

export type SetLearnerLbrLinkageInput = SetLearnerLbrLinkageParams & SetLearnerLbrLinkageRequestInput;

export type GetLearnerLbrLinkageOutput = {};

export type SetLearnerLbrLinkageOutput = {};
