/**
 * LbrEndpoint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LbrEndpoint DTOs
 *
 * DDD: Application DTOs for LbrEndpoint use cases.
 */

import type { CreateLbrEndpointRequestInput, GetLbrEndpointParams, ListLbrEndpointsParams, UpdateLbrEndpointParams, UpdateLbrEndpointRequestInput } from "@veritrace/core/adapters/types";

export type ListLbrEndpointsInput = ListLbrEndpointsParams;

export type CreateLbrEndpointInput = CreateLbrEndpointRequestInput;

export type GetLbrEndpointInput = GetLbrEndpointParams;

export type UpdateLbrEndpointInput = UpdateLbrEndpointParams & UpdateLbrEndpointRequestInput;

export type ListLbrEndpointsOutput = {};

export type CreateLbrEndpointOutput = {};

export type GetLbrEndpointOutput = {};

export type UpdateLbrEndpointOutput = {};
