/**
 * LedgerAdapter DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LedgerAdapter DTOs
 *
 * DDD: Application DTOs for LedgerAdapter use cases.
 */

import type { CreateLedgerAdapterRequestInput, GetLedgerAdapterParams, ListLedgerAdaptersParams } from "@veritrace/core/adapters/types";

export type ListLedgerAdaptersInput = ListLedgerAdaptersParams;

export type CreateLedgerAdapterInput = CreateLedgerAdapterRequestInput;

export type GetLedgerAdapterInput = GetLedgerAdapterParams;

export type ListLedgerAdaptersOutput = {};

export type CreateLedgerAdapterOutput = {};

export type GetLedgerAdapterOutput = {};
