/**
 * LbrEndpoint Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/adapters.openapi.types.js";
import { schemas } from "../schemas/adapters.schemas.js";

/**
 * Entity: LbrEndpointEntity
 * Description: Represents the LbrEndpoint domain model.
 * Source: schemas.LbrEndpoint
 * Type: Domain Entity (API)
 */
export const LbrEndpointEntitySchema = schemas.LbrEndpoint;
export type LbrEndpointEntity = components["schemas"]["LbrEndpoint"];
