/**
 * LedgerAdapter Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/adapters.openapi.types.js";
import { schemas } from "../schemas/adapters.schemas.js";

/**
 * Entity: LedgerAdapterEntity
 * Description: Represents the LedgerAdapter domain model.
 * Source: schemas.LedgerAdapter
 * Type: Domain Entity (API)
 */
export const LedgerAdapterEntitySchema = schemas.LedgerAdapter;
export type LedgerAdapterEntity = components["schemas"]["LedgerAdapter"];
