/**
 * Routes for AccessRequest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAccessRequest, getAccessRequest, listAccessRequests } from "../handlers/access-request.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function accessRequestRoutes(fastify: FastifyInstance) {
  // POST /v1/access-requests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/access-requests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await createAccessRequest(request, reply, deps);
      });
    }
  );


  // GET /v1/access-requests (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/access-requests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await listAccessRequests(request, reply, deps);
      });
    }
  );


  // GET /v1/access-requests/{accessRequestId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/access-requests/:accessRequestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { accessRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await getAccessRequest(request, reply, deps);
      });
    }
  );


}
