/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @veritrace/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@veritrace/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@veritrace/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@veritrace/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@veritrace/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@veritrace/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _adapters from "./adapters/index.js";
import * as _blocks from "./blocks/index.js";
import * as _commitments from "./commitments/index.js";
import * as _consents from "./consents/index.js";
import * as _exports from "./exports/index.js";
import * as _identity from "./identity/index.js";
import * as _spaces from "./spaces/index.js";
import * as _verifications from "./verifications/index.js";

// Export as namespaces
export const _shared = __shared;
export const adapters = _adapters;
export const blocks = _blocks;
export const commitments = _commitments;
export const consents = _consents;
export const exports = _exports;
export const identity = _identity;
export const spaces = _spaces;
export const verifications = _verifications;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@veritrace/core"; activity.types.*
//   - Direct exports: import * from "@veritrace/core/activity/types/index.js"
//   - Direct exports: import * from "@veritrace/core/activity/repositories/index.js"
//   - Direct exports: import * from "@veritrace/core/activity/models/index.js"
//   - Direct exports: import * from "@veritrace/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Adapters Service
export { schemas as AdaptersSchemas } from "./adapters/schemas/adapters.schemas.js";

// Blocks Service
export { schemas as BlocksSchemas } from "./blocks/schemas/blocks.schemas.js";

// Commitments Service
export { schemas as CommitmentsSchemas } from "./commitments/schemas/commitments.schemas.js";

// Consents Service
export { schemas as ConsentsSchemas } from "./consents/schemas/consents.schemas.js";

// Exports Service
export { schemas as ExportsSchemas } from "./exports/schemas/exports.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Spaces Service
export { schemas as SpacesSchemas } from "./spaces/schemas/spaces.schemas.js";

// Verifications Service
export { schemas as VerificationsSchemas } from "./verifications/schemas/verifications.schemas.js";

