/**
 * ExecuteListLbrEndpoints - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLbrEndpoints Use Case
 *
 * DDD: Application use case for list LbrEndpoint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLbrEndpointsInput, ListLbrEndpointsOutput } from "../dto/lbr-endpoint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LbrEndpointRepository } from "../ports";

export class ExecuteListLbrEndpoints {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lbrEndpoint: LbrEndpointRepository
  ) {}

  async execute(input: ListLbrEndpointsInput): Promise<ListLbrEndpointsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.lbrEndpoint.listLbrEndpoints({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLbrEndpointsOutput;
  }
}
