/**
 * ExecuteCreateLbrEndpoint - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateLbrEndpoint Use Case
 *
 * DDD: Application use case for create LbrEndpoint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateLbrEndpointInput, CreateLbrEndpointOutput } from "../dto/lbr-endpoint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LbrEndpointRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateLbrEndpoint {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lbrEndpoint: LbrEndpointRepository
  ) {}

  async execute(input: CreateLbrEndpointInput): Promise<CreateLbrEndpointOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec: baseUrl, kind, name, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.kind) {
      throw new ValidationError("kind is required");
    }
    if (!input.baseUrl) {
      throw new ValidationError("baseUrl is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (adapters domain)
    const entityId = this.idGenerator.adpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.lbrEndpoint.createLbrEndpoint({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateLbrEndpointOutput;
  }
}
