/**
 * ExecuteSetLearnerLbrLinkage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSetLearnerLbrLinkage Use Case
 *
 * DDD: Application use case for update LbrLinkage.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SetLearnerLbrLinkageInput, SetLearnerLbrLinkageOutput } from "../dto/lbr-linkage.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LbrLinkageRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSetLearnerLbrLinkage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lbrLinkage: LbrLinkageRepository
  ) {}

  async execute(input: SetLearnerLbrLinkageInput): Promise<SetLearnerLbrLinkageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).learnerId) {
      throw new ValidationError("learnerId is required");
    }
    const learnerId = (input as any).learnerId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.lbrLinkage.setLearnerLbrLinkage({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SetLearnerLbrLinkageOutput;
  }
}
