/**
 * ExecuteGetLedgerAdapter - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetLedgerAdapter Use Case
 *
 * DDD: Application use case for get LedgerAdapter.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetLedgerAdapterInput, GetLedgerAdapterOutput } from "../dto/ledger-adapter.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LedgerAdapterRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetLedgerAdapter {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ledgerAdapter: LedgerAdapterRepository
  ) {}

  async execute(input: GetLedgerAdapterInput): Promise<GetLedgerAdapterOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ledgerAdapterId) {
      throw new ValidationError("ledgerAdapterId is required");
    }
    const ledgeradapterId = (input as any).ledgerAdapterId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.ledgerAdapter.getLedgerAdapter({ ledgerAdapterId: ledgeradapterId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ledgeradapterId}`);
    }

    return entity as GetLedgerAdapterOutput;
  }
}
