/**
 * ExecuteListLedgerAdapters - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLedgerAdapters Use Case
 *
 * DDD: Application use case for list LedgerAdapter.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLedgerAdaptersInput, ListLedgerAdaptersOutput } from "../dto/ledger-adapter.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LedgerAdapterRepository } from "../ports";

export class ExecuteListLedgerAdapters {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ledgerAdapter: LedgerAdapterRepository
  ) {}

  async execute(input: ListLedgerAdaptersInput): Promise<ListLedgerAdaptersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ledgerAdapter.listLedgerAdapters({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLedgerAdaptersOutput;
  }
}
