/**
 * ExecuteGetLearnerLbrLinkage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetLearnerLbrLinkage Use Case
 *
 * DDD: Application use case for get LbrLinkage.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetLearnerLbrLinkageInput, GetLearnerLbrLinkageOutput } from "../dto/lbr-linkage.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { LbrLinkageRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetLearnerLbrLinkage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lbrLinkage: LbrLinkageRepository
  ) {}

  async execute(input: GetLearnerLbrLinkageInput): Promise<GetLearnerLbrLinkageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).learnerId) {
      throw new ValidationError("learnerId is required");
    }
    const learnerId = (input as any).learnerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.lbrLinkage.getLearnerLbrLinkage({ learnerId: learnerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${learnerId}`);
    }

    return entity as GetLearnerLbrLinkageOutput;
  }
}
