/**
 * LbrLinkageRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LbrLinkageRepository Port
 *
 * DDD: Application port for lbrlinkagerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLearnerLbrLinkageInput, GetLearnerLbrLinkageOutput, SetLearnerLbrLinkageInput, SetLearnerLbrLinkageOutput } from "../dto/lbr-linkage.dto";
export interface LbrLinkageRepository {
  getLearnerLbrLinkage(input: GetLearnerLbrLinkageInput): Promise<GetLearnerLbrLinkageOutput>;
  setLearnerLbrLinkage(input: SetLearnerLbrLinkageInput): Promise<SetLearnerLbrLinkageOutput>;
}

export type { GetLearnerLbrLinkageInput, GetLearnerLbrLinkageOutput, SetLearnerLbrLinkageInput, SetLearnerLbrLinkageOutput } from "../dto/lbr-linkage.dto";
