/**
 * DpiaEvidenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DpiaEvidenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DpiaEvidenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DpiaEvidenceRepository,
} from "@veritrace/services/spaces";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DpiaEvidenceRepositoryDdb } from "./dpia-evidence-repository.ddb.js";

/**
 * DpiaEvidenceRepositoryAdapter
 *
 * Implements DpiaEvidenceRepository port for infrastructure layer.
 */
export class DpiaEvidenceRepositoryAdapter implements DpiaEvidenceRepository {
  private readonly ddb: DpiaEvidenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DpiaEvidenceRepositoryDdb(this.dynamoClient);
  }

  async getDpiAEvidencePack(input: Parameters<DpiaEvidenceRepository['getDpiAEvidencePack']>[0]): Promise<Awaited<ReturnType<DpiaEvidenceRepository['getDpiAEvidencePack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDpiAEvidencePack(input);
  }
}
