/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./dpia-evidence-repository.ddb.js";
export * from "./necessity-decision-repository.ddb.js";
export * from "./space-repository.ddb.js";
export * from "./dpia-evidence-repository.adapter.js";
export * from "./necessity-decision-repository.adapter.js";
export * from "./space-repository.adapter.js";
