/**
 * NecessityDecisionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NecessityDecisionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements NecessityDecisionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  NecessityDecisionRepository,
} from "@veritrace/services/spaces";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { NecessityDecisionRepositoryDdb } from "./necessity-decision-repository.ddb.js";

/**
 * NecessityDecisionRepositoryAdapter
 *
 * Implements NecessityDecisionRepository port for infrastructure layer.
 */
export class NecessityDecisionRepositoryAdapter implements NecessityDecisionRepository {
  private readonly ddb: NecessityDecisionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new NecessityDecisionRepositoryDdb(this.dynamoClient);
  }

  async listNecessityDecisions(input: Parameters<NecessityDecisionRepository['listNecessityDecisions']>[0]): Promise<Awaited<ReturnType<NecessityDecisionRepository['listNecessityDecisions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listNecessityDecisions(input);
  }

  async recordNecessityDecision(input: Parameters<NecessityDecisionRepository['recordNecessityDecision']>[0]): Promise<Awaited<ReturnType<NecessityDecisionRepository['recordNecessityDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordNecessityDecision(input);
  }

  async getNecessityDecision(input: Parameters<NecessityDecisionRepository['getNecessityDecision']>[0]): Promise<Awaited<ReturnType<NecessityDecisionRepository['getNecessityDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getNecessityDecision(input);
  }
}
