/**
 * SpaceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpaceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SpaceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SpaceRepository,
} from "@veritrace/services/spaces";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SpaceRepositoryDdb } from "./space-repository.ddb.js";

/**
 * SpaceRepositoryAdapter
 *
 * Implements SpaceRepository port for infrastructure layer.
 */
export class SpaceRepositoryAdapter implements SpaceRepository {
  private readonly ddb: SpaceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SpaceRepositoryDdb(this.dynamoClient);
  }

  async listLearningSpaces(input: Parameters<SpaceRepository['listLearningSpaces']>[0]): Promise<Awaited<ReturnType<SpaceRepository['listLearningSpaces']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLearningSpaces(input);
  }

  async registerLearningSpace(input: Parameters<SpaceRepository['registerLearningSpace']>[0]): Promise<Awaited<ReturnType<SpaceRepository['registerLearningSpace']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerLearningSpace(input);
  }

  async getLearningSpace(input: Parameters<SpaceRepository['getLearningSpace']>[0]): Promise<Awaited<ReturnType<SpaceRepository['getLearningSpace']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLearningSpace(input);
  }
}
