/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the adapters domain.
 * Use these factories in tests to create test data.
 */

export { createLbrEndpoint } from "./lbr-endpoint/entity/lbr-endpoint.entity.factory.js";
export { createLedgerAdapter } from "./ledger-adapter/entity/ledger-adapter.entity.factory.js";
