/**
 * ExecuteCreateDeletionRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDeletionRequest Use Case
 *
 * DDD: Application use case for create DeletionRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDeletionRequestInput, CreateDeletionRequestOutput } from "../dto/deletion-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { DeletionRequestRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDeletionRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deletionRequest: DeletionRequestRepository
  ) {}

  async execute(input: CreateDeletionRequestInput): Promise<CreateDeletionRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.blkId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (blocks domain)
    const entityId = this.idGenerator.blkId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.deletionRequest.createDeletionRequest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDeletionRequestOutput;
  }
}
