/**
 * ExecuteListDeletionRequests - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDeletionRequests Use Case
 *
 * DDD: Application use case for list DeletionRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDeletionRequestsInput, ListDeletionRequestsOutput } from "../dto/deletion-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { DeletionRequestRepository } from "../ports";

export class ExecuteListDeletionRequests {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deletionRequest: DeletionRequestRepository
  ) {}

  async execute(input: ListDeletionRequestsInput): Promise<ListDeletionRequestsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.blkId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.deletionRequest.listDeletionRequests({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDeletionRequestsOutput;
  }
}
