/**
 * ExecuteEmitLearningBlock - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteEmitLearningBlock Use Case
 *
 * DDD: Application use case for get Block.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { EmitLearningBlockInput, EmitLearningBlockOutput } from "../dto/block.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { BlockRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteEmitLearningBlock {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly block: BlockRepository
  ) {}

  async execute(input: EmitLearningBlockInput): Promise<EmitLearningBlockOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.blkId();

    // All field names extracted from OpenAPI spec: activityId, anchorIfPolicyAllows, events, lbrEndpointId, learnerId, spaceId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).activityId) {
      throw new ValidationError("activityId is required");
    }
    const activityId = (input as any).activityId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.block.emitLearningBlock({ activityId: activityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${activityId}`);
    }

    return entity as EmitLearningBlockOutput;
  }
}
