/**
 * Routes for DpiaEvidence
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDpiAEvidencePack } from "../handlers/dpia-evidence.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dpiaEvidenceRoutes(fastify: FastifyInstance) {
  // GET /v1/spaces/{spaceId}/dpia-evidence (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/spaces/:spaceId/dpia-evidence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await getDpiAEvidencePack(request, reply, deps);
      });
    }
  );


}
