/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { dpiaEvidenceRoutes } from "./dpia-evidence.routes.js";
export { spaceRoutes } from "./space.routes.js";
export { necessityDecisionRoutes } from "./necessity-decision.routes.js";
