/**
 * Routes for NecessityDecision
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getNecessityDecision, listNecessityDecisions, recordNecessityDecision } from "../handlers/necessity-decision.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function necessityDecisionRoutes(fastify: FastifyInstance) {
  // GET /v1/spaces/{spaceId}/necessity-decisions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/spaces/:spaceId/necessity-decisions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await listNecessityDecisions(request, reply, deps);
      });
    }
  );


  // POST /v1/spaces/{spaceId}/necessity-decisions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/spaces/:spaceId/necessity-decisions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await recordNecessityDecision(request, reply, deps);
      });
    }
  );


  // GET /v1/spaces/{spaceId}/necessity-decisions/{necessityDecisionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/spaces/:spaceId/necessity-decisions/:necessityDecisionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { spaceId: string, necessityDecisionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await getNecessityDecision(request, reply, deps);
      });
    }
  );


}
