/**
 * Routes for Space
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLearningSpace, listLearningSpaces, registerLearningSpace } from "../handlers/space.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function spaceRoutes(fastify: FastifyInstance) {
  // GET /v1/spaces (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/spaces",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await listLearningSpaces(request, reply, deps);
      });
    }
  );


  // POST /v1/spaces (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/spaces",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await registerLearningSpace(request, reply, deps);
      });
    }
  );


  // GET /v1/spaces/{spaceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/spaces/:spaceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpacesDependenciesForRequest();
        await getLearningSpace(request, reply, deps);
      });
    }
  );


}
