/**
 * ExecuteListResearchExports - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListResearchExports Use Case
 *
 * DDD: Application use case for list Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListResearchExportsInput, ListResearchExportsOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { ExportRepository } from "../ports";

export class ExecuteListResearchExports {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: ListResearchExportsInput): Promise<ListResearchExportsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.expId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exportRepo.listResearchExports({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListResearchExportsOutput;
  }
}
