/**
 * LedgerAdapter Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { LedgerAdapterEntity } from "@veritrace/core/adapters/models/index.js";
import { adaptersSchemas } from "@veritrace/core/adapters";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "adp";

export function createLedgerAdapter(overrides: Partial<LedgerAdapterEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ledgerAdapterId: overrides.ledgerAdapterId ?? `ldg_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    networkId: overrides.networkId ?? faker.string.uuid(),
    status: overrides.status ?? "healthy",
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return adaptersSchemas.LedgerAdapter.parse(raw);
}

export function ledgerAdapterBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createLedgerAdapter(overrides));
}
