/**
 * Routes for Export
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createResearchExport, getResearchExport, listResearchExports } from "../handlers/export.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function exportRoutes(fastify: FastifyInstance) {
  // POST /v1/exports (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExportsDependenciesForRequest();
        await createResearchExport(request, reply, deps);
      });
    }
  );


  // GET /v1/exports (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExportsDependenciesForRequest();
        await listResearchExports(request, reply, deps);
      });
    }
  );


  // GET /v1/exports/{exportId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/exports/:exportId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExportsDependenciesForRequest();
        await getResearchExport(request, reply, deps);
      });
    }
  );


}
