/**
 * Handlers for TamperEvent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VerificationsDomainModule } from "../dependencies/verifications-ddd.dependencies.js";
import type { GetTamperEventInput, ListTamperEventsInput } from "@veritrace/services/verifications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/tamper-events
 * Operation: listTamperEvents
 */
export async function listTamperEvents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VerificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTamperEventsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.tamperEvents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/tamper-events/{tamperEventId}
 * Operation: getTamperEvent
 */
export async function getTamperEvent(
  request: FastifyRequest<{ Params: { tamperEventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VerificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetTamperEventInput = {
    tamperEventId: request.params.tamperEventId,
  };
  const result = await deps.useCases.tamperEvents.get.execute(input);
  return reply.code(200).send(result);
}


