/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the verifications domain.
 * Use these factories in tests to create test data.
 */

export { createTamperEvent } from "./tamper-event/entity/tamper-event.entity.factory.js";
export { createVerification } from "./verification/entity/verification.entity.factory.js";
