/**
 * ConsentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepository Port
 *
 * DDD: Application port for consentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateConsentGrantInput, CreateConsentGrantOutput, GetConsentInput, GetConsentOutput, ListConsentsInput, ListConsentsOutput } from "../dto/consent.dto";
export interface ConsentRepository {
  listConsents(input: ListConsentsInput): Promise<ListConsentsOutput>;
  createConsentGrant(input: CreateConsentGrantInput): Promise<CreateConsentGrantOutput>;
  getConsent(input: GetConsentInput): Promise<GetConsentOutput>;
}

export type { CreateConsentGrantInput, CreateConsentGrantOutput, GetConsentInput, GetConsentOutput, ListConsentsInput, ListConsentsOutput } from "../dto/consent.dto";
