/**
 * Repository interface for TamperEvent
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TamperEventEntity
} from "../models/tamper-event.entity.js";
import type {
  ListTamperEventsParams
} from "../types/index.js";
/**
 * TamperEventRepository Interface
 */
export interface TamperEventRepository extends ReadRepository<TamperEventEntity, string, ListTamperEventsParams> {

}
