/**
 * Repository interface for Verification
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  VerificationEntity
} from "../models/verification.entity.js";
import type {
  ListVerificationsParams,
  Verification
} from "../types/index.js";
/**
 * VerificationRepository Interface
 */
export interface VerificationRepository extends CreateReadRepository<VerificationEntity, Verification, string, ListVerificationsParams> {

}
