/**
 * Repository interface for DeletionRequest
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DeletionRequestEntity
} from "../models/deletion-request.entity.js";
import type {
  ListDeletionRequestsParams,
  DeletionRequest
} from "../types/index.js";
/**
 * DeletionRequestRepository Interface
 */
export interface DeletionRequestRepository extends CreateReadRepository<DeletionRequestEntity, DeletionRequest, string, ListDeletionRequestsParams> {

}
