/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { acknowledgeRoutes } from "./acknowledge.routes.js";
export { tamperEventRoutes } from "./tamper-event.routes.js";
export { verificationRoutes } from "./verification.routes.js";
