/**
 * Routes for TamperEvent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getTamperEvent, listTamperEvents } from "../handlers/tamper-event.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function tamperEventRoutes(fastify: FastifyInstance) {
  // GET /v1/tamper-events (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/tamper-events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVerificationsDependenciesForRequest();
        await listTamperEvents(request, reply, deps);
      });
    }
  );


  // GET /v1/tamper-events/{tamperEventId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/tamper-events/:tamperEventId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { tamperEventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVerificationsDependenciesForRequest();
        await getTamperEvent(request, reply, deps);
      });
    }
  );


}
