/**
 * GetCommitment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCommitmentParams } from "@veritrace/core/commitments";

export function createGetCommitmentRequest(overrides: Partial<GetCommitmentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
