/**
 * Consents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Consents Domain Module - Composition root
 *
 * DDD: Composition root for consents domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AccessRequestRepositoryAdapter,
  ConsentRepositoryAdapter,
  DecideRepositoryAdapter,
  RevokeRepositoryAdapter,
} from "@veritrace/adapters/consents";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAccessRequest,
  ExecuteCreateConsentGrant,
  ExecuteDecideAccessRequest,
  ExecuteGetAccessRequest,
  ExecuteGetConsent,
  ExecuteListAccessRequests,
  ExecuteListConsents,
  ExecuteRevokeConsent,
} from "@veritrace/services/consents/usecases";
// Ports (interfaces)
import type {
  AccessRequestRepository,
  ConsentRepository,
  DecideRepository,
  RevokeRepository,
} from "@veritrace/services/consents/ports";

export interface ConsentsDomainModule {
  repos: {
    accessRequests: AccessRequestRepository;
    consents: ConsentRepository;
    decides: DecideRepository;
    revokes: RevokeRepository;
  };
  useCases: {
    accessRequests: {
      create: ExecuteCreateAccessRequest;
      get: ExecuteGetAccessRequest;
      list: ExecuteListAccessRequests;
    };
    consents: {
      create: ExecuteCreateConsentGrant;
      get: ExecuteGetConsent;
      list: ExecuteListConsents;
    };
    decides: {
      get: ExecuteDecideAccessRequest;
    };
    revokes: {
      get: ExecuteRevokeConsent;
    };
  };
}

export function buildConsentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ConsentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      accessRequests?: AccessRequestRepository;
      consents?: ConsentRepository;
      decides?: DecideRepository;
      revokes?: RevokeRepository;
    } = {};

    obj.accessRequests = new AccessRequestRepositoryAdapter(dynamoClient);
    obj.consents = new ConsentRepositoryAdapter(dynamoClient);
    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    obj.revokes = new RevokeRepositoryAdapter(dynamoClient);
    return {
      accessRequests: obj.accessRequests!,
      consents: obj.consents!,
      decides: obj.decides!,
      revokes: obj.revokes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    accessRequests: {
      create: new ExecuteCreateAccessRequest(executionContext, idGenerator, repos.accessRequests),
      get: new ExecuteGetAccessRequest(executionContext, idGenerator, repos.accessRequests),
      list: new ExecuteListAccessRequests(executionContext, idGenerator, repos.accessRequests),
    },
    consents: {
      create: new ExecuteCreateConsentGrant(executionContext, idGenerator, repos.consents),
      get: new ExecuteGetConsent(executionContext, idGenerator, repos.consents),
      list: new ExecuteListConsents(executionContext, idGenerator, repos.consents),
    },
    decides: {
      get: new ExecuteDecideAccessRequest(executionContext, idGenerator, repos.decides),
    },
    revokes: {
      get: new ExecuteRevokeConsent(executionContext, idGenerator, repos.revokes),
    },
  };
  return { repos, useCases: useCases as ConsentsDomainModule["useCases"] };
}
