/**
 * NecessityDecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NecessityDecisionRepository Port
 *
 * DDD: Application port for necessitydecisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetNecessityDecisionInput, GetNecessityDecisionOutput, ListNecessityDecisionsInput, ListNecessityDecisionsOutput, RecordNecessityDecisionInput, RecordNecessityDecisionOutput } from "../dto/necessity-decision.dto";
export interface NecessityDecisionRepository {
  listNecessityDecisions(input: ListNecessityDecisionsInput): Promise<ListNecessityDecisionsOutput>;
  recordNecessityDecision(input: RecordNecessityDecisionInput): Promise<RecordNecessityDecisionOutput>;
  getNecessityDecision(input: GetNecessityDecisionInput): Promise<GetNecessityDecisionOutput>;
}

export type { GetNecessityDecisionInput, GetNecessityDecisionOutput, ListNecessityDecisionsInput, ListNecessityDecisionsOutput, RecordNecessityDecisionInput, RecordNecessityDecisionOutput } from "../dto/necessity-decision.dto";
