/**
 * SpaceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpaceRepository Port
 *
 * DDD: Application port for spacerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLearningSpaceInput, GetLearningSpaceOutput, ListLearningSpacesInput, ListLearningSpacesOutput, RegisterLearningSpaceInput, RegisterLearningSpaceOutput } from "../dto/space.dto";
export interface SpaceRepository {
  listLearningSpaces(input: ListLearningSpacesInput): Promise<ListLearningSpacesOutput>;
  registerLearningSpace(input: RegisterLearningSpaceInput): Promise<RegisterLearningSpaceOutput>;
  getLearningSpace(input: GetLearningSpaceInput): Promise<GetLearningSpaceOutput>;
}

export type { GetLearningSpaceInput, GetLearningSpaceOutput, ListLearningSpacesInput, ListLearningSpacesOutput, RegisterLearningSpaceInput, RegisterLearningSpaceOutput } from "../dto/space.dto";
