/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAdaptersDomainModule } from "./adapters/dependencies/adapters-ddd.dependencies.js";
export { buildBlocksDomainModule } from "./blocks/dependencies/blocks-ddd.dependencies.js";
export { buildCommitmentsDomainModule } from "./commitments/dependencies/commitments-ddd.dependencies.js";
export { buildConsentsDomainModule } from "./consents/dependencies/consents-ddd.dependencies.js";
export { buildExportsDomainModule } from "./exports/dependencies/exports-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildSpacesDomainModule } from "./spaces/dependencies/spaces-ddd.dependencies.js";
export { buildVerificationsDomainModule } from "./verifications/dependencies/verifications-ddd.dependencies.js";

// Export all domain dependency types
export type { AdaptersDomainModule } from "./adapters/dependencies/adapters-ddd.dependencies.js";
export type { BlocksDomainModule } from "./blocks/dependencies/blocks-ddd.dependencies.js";
export type { CommitmentsDomainModule } from "./commitments/dependencies/commitments-ddd.dependencies.js";
export type { ConsentsDomainModule } from "./consents/dependencies/consents-ddd.dependencies.js";
export type { ExportsDomainModule } from "./exports/dependencies/exports-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { SpacesDomainModule } from "./spaces/dependencies/spaces-ddd.dependencies.js";
export type { VerificationsDomainModule } from "./verifications/dependencies/verifications-ddd.dependencies.js";
