/**
 * Commitment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Commitment DTOs
 *
 * DDD: Application DTOs for Commitment use cases.
 */

import type { AnchorCommitmentRequestInput, GetCommitmentParams, ListCommitmentsParams } from "@veritrace/core/commitments/types";

export type ListCommitmentsInput = ListCommitmentsParams;

export type AnchorCommitmentInput = AnchorCommitmentRequestInput;

export type GetCommitmentInput = GetCommitmentParams;

export type ListCommitmentsOutput = {};

export type AnchorCommitmentOutput = {};

export type GetCommitmentOutput = {};
