/**
 * BlockRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BlockRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BlockRepository,
} from "@veritrace/services/blocks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BlockRepositoryDdb } from "./block-repository.ddb.js";

/**
 * BlockRepositoryAdapter
 *
 * Implements BlockRepository port for infrastructure layer.
 */
export class BlockRepositoryAdapter implements BlockRepository {
  private readonly ddb: BlockRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BlockRepositoryDdb(this.dynamoClient);
  }

  async listLearningBlocks(input: Parameters<BlockRepository['listLearningBlocks']>[0]): Promise<Awaited<ReturnType<BlockRepository['listLearningBlocks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLearningBlocks(input);
  }

  async emitLearningBlock(input: Parameters<BlockRepository['emitLearningBlock']>[0]): Promise<Awaited<ReturnType<BlockRepository['emitLearningBlock']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.emitLearningBlock(input);
  }

  async getLearningBlockMeta(input: Parameters<BlockRepository['getLearningBlockMeta']>[0]): Promise<Awaited<ReturnType<BlockRepository['getLearningBlockMeta']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLearningBlockMeta(input);
  }
}
