/**
 * DeletionRequestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeletionRequestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeletionRequestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeletionRequestRepository,
} from "@veritrace/services/blocks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeletionRequestRepositoryDdb } from "./deletion-request-repository.ddb.js";

/**
 * DeletionRequestRepositoryAdapter
 *
 * Implements DeletionRequestRepository port for infrastructure layer.
 */
export class DeletionRequestRepositoryAdapter implements DeletionRequestRepository {
  private readonly ddb: DeletionRequestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeletionRequestRepositoryDdb(this.dynamoClient);
  }

  async createDeletionRequest(input: Parameters<DeletionRequestRepository['createDeletionRequest']>[0]): Promise<Awaited<ReturnType<DeletionRequestRepository['createDeletionRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDeletionRequest(input);
  }

  async listDeletionRequests(input: Parameters<DeletionRequestRepository['listDeletionRequests']>[0]): Promise<Awaited<ReturnType<DeletionRequestRepository['listDeletionRequests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDeletionRequests(input);
  }

  async getDeletionRequest(input: Parameters<DeletionRequestRepository['getDeletionRequest']>[0]): Promise<Awaited<ReturnType<DeletionRequestRepository['getDeletionRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDeletionRequest(input);
  }
}
