/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./block-repository.ddb.js";
export * from "./deletion-request-repository.ddb.js";
export * from "./block-repository.adapter.js";
export * from "./deletion-request-repository.adapter.js";
