/**
 * UpdateLbrEndpoint handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateLbrEndpoint } from "@veritrace/api-server/domains/adapters/handlers";
import type { AdaptersDDDDependencies } from "@veritrace/api-server/domains/adapters";
import { createLbrEndpoint as createLbrEndpointEntity } from "@veritrace/factories/adapters";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { ADAPTERS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateLbrEndpoint", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdaptersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdaptersDDDDependencies>(
      ADAPTERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createLbrEndpointEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { lbrEndpointId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateLbrEndpoint, "execute").mockResolvedValue(useCaseResult);

    await updateLbrEndpoint(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateLbrEndpoint.execute).toHaveBeenCalledWith(expect.objectContaining({ lbrEndpointId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
