/**
 * GetDpiaEvidence DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDpiAEvidencePackParams } from "@veritrace/core/spaces";

export function createGetDpiaEvidenceRequest(overrides: Partial<GetDpiAEvidencePackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
