/**
 * Commitments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Commitments Domain Module - Composition root
 *
 * DDD: Composition root for commitments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CommitmentRepositoryAdapter,
} from "@veritrace/adapters/commitments";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAnchorCommitment,
  ExecuteGetCommitment,
  ExecuteListCommitments,
} from "@veritrace/services/commitments/usecases";
// Ports (interfaces)
import type {
  CommitmentRepository,
} from "@veritrace/services/commitments/ports";

export interface CommitmentsDomainModule {
  repos: {
    commitments: CommitmentRepository;
  };
  useCases: {
    commitments: {
      get: ExecuteGetCommitment;
      list: ExecuteListCommitments;
    };
  };
}

export function buildCommitmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CommitmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      commitments?: CommitmentRepository;
    } = {};

    obj.commitments = new CommitmentRepositoryAdapter(dynamoClient);
    return {
      commitments: obj.commitments!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    commitments: {
      get: new ExecuteGetCommitment(executionContext, idGenerator, repos.commitments),
      list: new ExecuteListCommitments(executionContext, idGenerator, repos.commitments),
    },
  };
  return { repos, useCases: useCases as CommitmentsDomainModule["useCases"] };
}
