/**
 * Handlers for DpiaEvidence
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SpacesDomainModule } from "../dependencies/spaces-ddd.dependencies.js";
import type { GetDpiAEvidencePackInput } from "@veritrace/services/spaces";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/spaces/{spaceId}/dpia-evidence
 * Operation: getDpiAEvidencePack
 */
export async function getDpiAEvidencePack(
  request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SpacesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDpiAEvidencePackInput = {
    spaceId: request.params.spaceId,
  };
  const result = await deps.useCases.dpiaEvidences.get.execute(input);
  return reply.code(200).send(result);
}


