/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./dpia-evidence.handlers.js";
export * from "./necessity-decision.handlers.js";
export * from "./space.handlers.js";
