/**
 * Handlers for Space
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SpacesDomainModule } from "../dependencies/spaces-ddd.dependencies.js";
import type { GetLearningSpaceInput, ListLearningSpacesInput, RegisterLearningSpaceInput } from "@veritrace/services/spaces";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/spaces
 * Operation: listLearningSpaces
 */
export async function listLearningSpaces(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], researchCollectionEnabled?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SpacesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLearningSpacesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.spaces.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/spaces
 * Operation: registerLearningSpace
 */
export async function registerLearningSpace(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SpacesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterLearningSpaceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.spaces.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/spaces/{spaceId}
 * Operation: getLearningSpace
 */
export async function getLearningSpace(
  request: FastifyRequest<{ Params: { spaceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SpacesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLearningSpaceInput = {
    spaceId: request.params.spaceId,
  };
  const result = await deps.useCases.spaces.get.execute(input);
  return reply.code(200).send(result);
}


