/**
 * GetTamperEvent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTamperEventParams } from "@veritrace/core/verifications";

export function createGetTamperEventRequest(overrides: Partial<GetTamperEventParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
