/**
 * GetVerification handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getVerification } from "@veritrace/api-server/domains/verifications/handlers";
import type { VerificationsDDDDependencies } from "@veritrace/api-server/domains/verifications";
import { createVerification as createVerificationEntity } from "@veritrace/factories/verifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { VERIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetVerification", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VerificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VerificationsDDDDependencies>(
      VERIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createVerificationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetVerification, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { verificationId: entity.id };

    await getVerification(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetVerification.execute).toHaveBeenCalledWith(expect.objectContaining({ verificationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { verificationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetVerification, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getVerification(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
