/**
 * ListVerifications handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listVerifications } from "@veritrace/api-server/domains/verifications/handlers";
import type { VerificationsDDDDependencies } from "@veritrace/api-server/domains/verifications";
import { createVerification as createVerificationEntity } from "@veritrace/factories/verifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { VERIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListVerifications", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VerificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VerificationsDDDDependencies>(
      VERIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createVerificationEntity({ orgId }),
      createVerificationEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListVerifications, "execute").mockResolvedValue(useCaseResult);

    await listVerifications(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListVerifications.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
