/**
 * VerifyLearningBlock handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { verifyLearningBlock } from "@veritrace/api-server/domains/verifications/handlers";
import type { VerificationsDDDDependencies } from "@veritrace/api-server/domains/verifications";
import { createVerification as createVerificationEntity } from "@veritrace/factories/verifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { VERIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("VerifyLearningBlock", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VerificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VerificationsDDDDependencies>(
      VERIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createVerificationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeVerifyLearningBlock, "execute").mockResolvedValue(useCaseResult);

    await verifyLearningBlock(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeVerifyLearningBlock.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
