/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@veritrace/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@veritrace/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@veritrace/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _adapters from "./adapters/index.js";
import * as _blocks from "./blocks/index.js";
import * as _commitments from "./commitments/index.js";
import * as _consents from "./consents/index.js";
import * as _exports from "./exports/index.js";
import * as _identity from "./identity/index.js";
import * as _spaces from "./spaces/index.js";
import * as _verifications from "./verifications/index.js";

// Export as namespaces
export const adapters = _adapters;
export const blocks = _blocks;
export const commitments = _commitments;
export const consents = _consents;
export const exports = _exports;
export const identity = _identity;
export const spaces = _spaces;
export const verifications = _verifications;
