/**
 * CreateLedgerAdapter handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createLedgerAdapter } from "@veritrace/api-server/domains/adapters/handlers";
import type { AdaptersDDDDependencies } from "@veritrace/api-server/domains/adapters";
import { createLedgerAdapter as createLedgerAdapterEntity } from "@veritrace/factories/adapters";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { ADAPTERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateLedgerAdapter", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdaptersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdaptersDDDDependencies>(
      ADAPTERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createLedgerAdapterEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateLedgerAdapter, "execute").mockResolvedValue(useCaseResult);

    await createLedgerAdapter(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateLedgerAdapter.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
