/**
 * GetLedgerAdapter handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getLedgerAdapter } from "@veritrace/api-server/domains/adapters/handlers";
import type { AdaptersDDDDependencies } from "@veritrace/api-server/domains/adapters";
import { createLedgerAdapter as createLedgerAdapterEntity } from "@veritrace/factories/adapters";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { ADAPTERS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetLedgerAdapter", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdaptersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdaptersDDDDependencies>(
      ADAPTERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createLedgerAdapterEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetLedgerAdapter, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { ledgerAdapterId: entity.id };

    await getLedgerAdapter(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetLedgerAdapter.execute).toHaveBeenCalledWith(expect.objectContaining({ ledgerAdapterId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { ledgerAdapterId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetLedgerAdapter, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getLedgerAdapter(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
