/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-ledger-adapter.handler.test.js";
export * from "./get-ledger-adapter.handler.test.js";
export * from "./list-ledger-adapters.handler.test.js";
