/**
 * ListLedgerAdapters handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listLedgerAdapters } from "@veritrace/api-server/domains/adapters/handlers";
import type { AdaptersDDDDependencies } from "@veritrace/api-server/domains/adapters";
import { createLedgerAdapter as createLedgerAdapterEntity } from "@veritrace/factories/adapters";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { ADAPTERS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListLedgerAdapters", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AdaptersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AdaptersDDDDependencies>(
      ADAPTERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createLedgerAdapterEntity({ orgId }),
      createLedgerAdapterEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListLedgerAdapters, "execute").mockResolvedValue(useCaseResult);

    await listLedgerAdapters(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListLedgerAdapters.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
