/**
 * Exports DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exports Domain Module - Composition root
 *
 * DDD: Composition root for exports domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExportRepositoryAdapter,
} from "@veritrace/adapters/exports";
import { getIdGeneratorService } from "@veritrace/adapters";
import type { AdapterDynamoDBClient } from "@veritrace/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateResearchExport,
  ExecuteGetResearchExport,
  ExecuteListResearchExports,
} from "@veritrace/services/exports/usecases";
// Ports (interfaces)
import type {
  ExportRepository,
} from "@veritrace/services/exports/ports";

export interface ExportsDomainModule {
  repos: {
    exports: ExportRepository;
  };
  useCases: {
    exports: {
      create: ExecuteCreateResearchExport;
      get: ExecuteGetResearchExport;
      list: ExecuteListResearchExports;
    };
  };
}

export function buildExportsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ExportsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      exports?: ExportRepository;
    } = {};

    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    return {
      exports: obj.exports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    exports: {
      create: new ExecuteCreateResearchExport(executionContext, idGenerator, repos.exports),
      get: new ExecuteGetResearchExport(executionContext, idGenerator, repos.exports),
      list: new ExecuteListResearchExports(executionContext, idGenerator, repos.exports),
    },
  };
  return { repos, useCases: useCases as ExportsDomainModule["useCases"] };
}
