/**
 * Repository interface for LbrEndpoint
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LbrEndpointEntity
} from "../models/lbr-endpoint.entity.js";
import type {
  ListLbrEndpointsParams,
  LbrEndpoint,
  UpdateLbrEndpointRequestInput
} from "../types/index.js";
/**
 * LbrEndpointRepository Interface
 */
export interface LbrEndpointRepository extends CreateUpdateReadRepository<LbrEndpointEntity, LbrEndpoint, UpdateLbrEndpointRequestInput, string, ListLbrEndpointsParams> {

}
