/**
 * Repository interface for LedgerAdapter
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LedgerAdapterEntity
} from "../models/ledger-adapter.entity.js";
import type {
  ListLedgerAdaptersParams,
  LedgerAdapter
} from "../types/index.js";
/**
 * LedgerAdapterRepository Interface
 */
export interface LedgerAdapterRepository extends CreateReadRepository<LedgerAdapterEntity, LedgerAdapter, string, ListLedgerAdaptersParams> {

}
