/**
 * TamperEvent Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/verifications.openapi.types.js";
import { schemas } from "../schemas/verifications.schemas.js";

/**
 * Entity: TamperEventEntity
 * Description: Represents the TamperEvent domain model.
 * Source: schemas.TamperEvent
 * Type: Domain Entity (API)
 */
export const TamperEventEntitySchema = schemas.TamperEvent;
export type TamperEventEntity = components["schemas"]["TamperEvent"];
