/**
 * Verification Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/verifications.openapi.types.js";
import { schemas } from "../schemas/verifications.schemas.js";

/**
 * Entity: VerificationEntity
 * Description: Represents the Verification domain model.
 * Source: schemas.Verification
 * Type: Domain Entity (API)
 */
export const VerificationEntitySchema = schemas.Verification;
export type VerificationEntity = components["schemas"]["Verification"];
