/**
 * TamperEvent Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: verifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { TamperEventEntity } from "@veritrace/core/verifications/models/index.js";
import { verificationsSchemas } from "@veritrace/core/verifications";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "vrf";

export function createTamperEvent(overrides: Partial<TamperEventEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    blockId: overrides.blockId ?? `blk_${ulid().toLowerCase()}`,
    detectedAt: overrides.detectedAt ?? new Date().toISOString(),
    status: overrides.status ?? "open",
    tamperEventId: overrides.tamperEventId ?? `tmp_${ulid().toLowerCase()}`,
    verificationId: overrides.verificationId ?? `vrf_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return verificationsSchemas.TamperEvent.parse(raw);
}

export function tamperEventBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTamperEvent(overrides));
}
