/**
 * NecessityDecision Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/spaces.openapi.types.js";
import { schemas } from "../schemas/spaces.schemas.js";

/**
 * Entity: NecessityDecisionEntity
 * Description: Represents the NecessityDecision domain model.
 * Source: schemas.NecessityDecision
 * Type: Domain Entity (API)
 */
export const NecessityDecisionEntitySchema = schemas.NecessityDecision;
export type NecessityDecisionEntity = components["schemas"]["NecessityDecision"];
