/**
 * Repository interface for NecessityDecision
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: spaces
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  NecessityDecisionEntity
} from "../models/necessity-decision.entity.js";
import type {
  ListNecessityDecisionsParams,
  NecessityDecision
} from "../types/index.js";
/**
 * NecessityDecisionRepository Interface
 */
export interface NecessityDecisionRepository extends CreateReadRepository<NecessityDecisionEntity, NecessityDecision, string, ListNecessityDecisionsParams> {

}
