/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./lbr-endpoint-repository.ddb.js";
export * from "./lbr-linkage-repository.ddb.js";
export * from "./ledger-adapter-repository.ddb.js";
export * from "./lbr-endpoint-repository.adapter.js";
export * from "./lbr-linkage-repository.adapter.js";
export * from "./ledger-repository.adapter.js";
