/**
 * LbrLinkageRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LbrLinkageRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LbrLinkageRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LbrLinkageRepository,
} from "@veritrace/services/adapters";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LbrLinkageRepositoryDdb } from "./lbr-linkage-repository.ddb.js";

/**
 * LbrLinkageRepositoryAdapter
 *
 * Implements LbrLinkageRepository port for infrastructure layer.
 */
export class LbrLinkageRepositoryAdapter implements LbrLinkageRepository {
  private readonly ddb: LbrLinkageRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LbrLinkageRepositoryDdb(this.dynamoClient);
  }

  async getLearnerLbrLinkage(input: Parameters<LbrLinkageRepository['getLearnerLbrLinkage']>[0]): Promise<Awaited<ReturnType<LbrLinkageRepository['getLearnerLbrLinkage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLearnerLbrLinkage(input);
  }

  async setLearnerLbrLinkage(input: Parameters<LbrLinkageRepository['setLearnerLbrLinkage']>[0]): Promise<Awaited<ReturnType<LbrLinkageRepository['setLearnerLbrLinkage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setLearnerLbrLinkage(input);
  }
}
