/**
 * LbrEndpointRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LbrEndpointRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LbrEndpointRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LbrEndpointRepository,
} from "@veritrace/services/adapters";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LbrEndpointRepositoryDdb } from "./lbr-endpoint-repository.ddb.js";

/**
 * LbrEndpointRepositoryAdapter
 *
 * Implements LbrEndpointRepository port for infrastructure layer.
 */
export class LbrEndpointRepositoryAdapter implements LbrEndpointRepository {
  private readonly ddb: LbrEndpointRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LbrEndpointRepositoryDdb(this.dynamoClient);
  }

  async listLbrEndpoints(input: Parameters<LbrEndpointRepository['listLbrEndpoints']>[0]): Promise<Awaited<ReturnType<LbrEndpointRepository['listLbrEndpoints']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLbrEndpoints(input);
  }

  async createLbrEndpoint(input: Parameters<LbrEndpointRepository['createLbrEndpoint']>[0]): Promise<Awaited<ReturnType<LbrEndpointRepository['createLbrEndpoint']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLbrEndpoint(input);
  }

  async getLbrEndpoint(input: Parameters<LbrEndpointRepository['getLbrEndpoint']>[0]): Promise<Awaited<ReturnType<LbrEndpointRepository['getLbrEndpoint']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLbrEndpoint(input);
  }

  async updateLbrEndpoint(input: Parameters<LbrEndpointRepository['updateLbrEndpoint']>[0]): Promise<Awaited<ReturnType<LbrEndpointRepository['updateLbrEndpoint']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateLbrEndpoint(input);
  }
}
