/**
 * LedgerAdapterRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LedgerAdapterRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LedgerAdapterRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LedgerAdapterRepository,
} from "@veritrace/services/adapters";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LedgerAdapterRepositoryDdb } from "./ledger-adapter-repository.ddb.js";

/**
 * LedgerAdapterRepositoryAdapter
 *
 * Implements LedgerAdapterRepository port for infrastructure layer.
 */
export class LedgerAdapterRepositoryAdapter implements LedgerAdapterRepository {
  private readonly ddb: LedgerAdapterRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LedgerAdapterRepositoryDdb(this.dynamoClient);
  }

  async listLedgerAdapters(input: Parameters<LedgerAdapterRepository['listLedgerAdapters']>[0]): Promise<Awaited<ReturnType<LedgerAdapterRepository['listLedgerAdapters']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLedgerAdapters(input);
  }

  async createLedgerAdapter(input: Parameters<LedgerAdapterRepository['createLedgerAdapter']>[0]): Promise<Awaited<ReturnType<LedgerAdapterRepository['createLedgerAdapter']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLedgerAdapter(input);
  }

  async getLedgerAdapter(input: Parameters<LedgerAdapterRepository['getLedgerAdapter']>[0]): Promise<Awaited<ReturnType<LedgerAdapterRepository['getLedgerAdapter']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLedgerAdapter(input);
  }
}
