/**
 * ListLbrEndpoint DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListLbrEndpointsParams } from "@veritrace/core/adapters";

export function createListLbrEndpointRequest(overrides: Partial<ListLbrEndpointsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
