/**
 * CommitmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CommitmentRepository Port
 *
 * DDD: Application port for commitmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AnchorCommitmentInput, AnchorCommitmentOutput, GetCommitmentInput, GetCommitmentOutput, ListCommitmentsInput, ListCommitmentsOutput } from "../dto/commitment.dto";
export interface CommitmentRepository {
  listCommitments(input: ListCommitmentsInput): Promise<ListCommitmentsOutput>;
  anchorCommitment(input: AnchorCommitmentInput): Promise<AnchorCommitmentOutput>;
  getCommitment(input: GetCommitmentInput): Promise<GetCommitmentOutput>;
}

export type { AnchorCommitmentInput, AnchorCommitmentOutput, GetCommitmentInput, GetCommitmentOutput, ListCommitmentsInput, ListCommitmentsOutput } from "../dto/commitment.dto";
