/**
 * GetLearningBlockMeta handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getLearningBlockMeta } from "@veritrace/api-server/domains/blocks/handlers";
import type { BlocksDDDDependencies } from "@veritrace/api-server/domains/blocks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veritrace/tests/shared";
import { BLOCKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetLearningBlockMeta", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BlocksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BlocksDDDDependencies>(
      BLOCKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetLearningBlockMeta, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { blockId: entity.id };

    await getLearningBlockMeta(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetLearningBlockMeta.execute).toHaveBeenCalledWith(expect.objectContaining({ blockId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { blockId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetLearningBlockMeta, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getLearningBlockMeta(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
