/**
 * ExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExportRepository,
} from "@veritrace/services/exports";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExportRepositoryDdb } from "./export-repository.ddb.js";

/**
 * ExportRepositoryAdapter
 *
 * Implements ExportRepository port for infrastructure layer.
 */
export class ExportRepositoryAdapter implements ExportRepository {
  private readonly ddb: ExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExportRepositoryDdb(this.dynamoClient);
  }

  async listResearchExports(input: Parameters<ExportRepository['listResearchExports']>[0]): Promise<Awaited<ReturnType<ExportRepository['listResearchExports']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listResearchExports(input);
  }

  async createResearchExport(input: Parameters<ExportRepository['createResearchExport']>[0]): Promise<Awaited<ReturnType<ExportRepository['createResearchExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createResearchExport(input);
  }

  async getResearchExport(input: Parameters<ExportRepository['getResearchExport']>[0]): Promise<Awaited<ReturnType<ExportRepository['getResearchExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getResearchExport(input);
  }
}
