/**
 * ExecuteGetCommitment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCommitment Use Case
 *
 * DDD: Application use case for get Commitment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCommitmentInput, GetCommitmentOutput } from "../dto/commitment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { CommitmentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCommitment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly commitment: CommitmentRepository
  ) {}

  async execute(input: GetCommitmentInput): Promise<GetCommitmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).commitmentId) {
      throw new ValidationError("commitmentId is required");
    }
    const commitmentId = (input as any).commitmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.commitment.getCommitment({ commitmentId: commitmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${commitmentId}`);
    }

    return entity as GetCommitmentOutput;
  }
}
