/**
 * ExecuteListCommitments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: commitments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCommitments Use Case
 *
 * DDD: Application use case for list Commitment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCommitmentsInput, ListCommitmentsOutput } from "../dto/commitment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veritrace/services/_shared/index.js";
import type { CommitmentRepository } from "../ports";

export class ExecuteListCommitments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly commitment: CommitmentRepository
  ) {}

  async execute(input: ListCommitmentsInput): Promise<ListCommitmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.commitment.listCommitments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCommitmentsOutput;
  }
}
