/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List research exports */
        get: operations["listResearchExports"];
        put?: never;
        /**
         * Create a research export package
         * @description Bundle verified blocks with consent artefacts and necessity summary.
         *     Generation is blocked if any selected block failed verification (unless policy allows no_anchor).
         */
        post: operations["createResearchExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get research export by id */
        get: operations["getResearchExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Prefixed consent-grant identifier.
         * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        ConsentId: string;
        /** @enum {string} */
        ResearchExportStatus: "pending" | "ready" | "failed";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Prefixed research-export identifier.
         * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        ExportId: string;
        /**
         * @description Prefixed learning-space identifier.
         * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        SpaceId: string;
        /**
         * @description Prefixed ULID-style tenant operator user identifier.
         * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        UserId: string;
        /**
         * @description Prefixed learning-block identifier.
         * @example blk_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        BlockId: string;
        /**
         * @description Prefixed verification-result identifier.
         * @example vrf_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        VerificationId: string;
        /**
         * @description Prefixed learner identifier.
         * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        LearnerId: string;
        /** @description Consent artefact included in an ethics-ready export package. */
        ConsentArtefactSummary: {
            /**
             * @description Prefixed consent-grant identifier.
             * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            consentId: string;
            purpose: string;
            /** @enum {string} */
            status: "active" | "revoked" | "expired";
            /** Format: date-time */
            expiresAt?: string;
            /**
             * @description Prefixed learner identifier.
             * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            learnerId?: string;
            /**
             * @description Prefixed ULID-style tenant operator user identifier.
             * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            researcherId?: string;
        };
        /**
         * @description Prefixed blockchain-necessity decision identifier.
         * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
         */
        NecessityDecisionId: string;
        /** @description Necessity decision summary for ethics boards (no PII). */
        NecessitySummary: {
            /**
             * @description Prefixed blockchain-necessity decision identifier.
             * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            necessityDecisionId?: string;
            /**
             * @description Prefixed learning-space identifier.
             * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            spaceId?: string;
            /** @enum {string} */
            outcome?: "permissioned" | "permissionless" | "no_chain";
            useBlockchain?: boolean;
            rationaleExcerpt?: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        /**
         * @description Ethics-board oriented checklist for the export package contents
         *     (proofs, consent artefacts, necessity summary).
         */
        EthicsPackageSummary: {
            studyId?: string;
            studyTitle?: string;
            includesVerificationProofs: boolean;
            includesConsentArtefacts: boolean;
            includesNecessitySummary: boolean;
            blockCount: number;
            validVerificationCount?: number;
            noAnchorCount?: number;
            mismatchCount?: number;
            /**
             * Format: uri
             * @description Optional read-only share link for ethics board review.
             */
            ethicsShareUrl?: string;
        };
        /** @description Verified research export package with proofs and consent artefacts. */
        ResearchExport: {
            /**
             * @description Prefixed research-export identifier.
             * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            exportId: string;
            /**
             * @description Prefixed consent-grant identifier.
             * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            consentId: string;
            /**
             * @description Prefixed learning-space identifier.
             * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            spaceId?: string;
            /**
             * @description Prefixed ULID-style tenant operator user identifier.
             * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            researcherId?: string;
            /** @enum {string} */
            status: "pending" | "ready" | "failed";
            blockIds: string[];
            verificationIds: string[];
            consentArtefacts?: {
                /**
                 * @description Prefixed consent-grant identifier.
                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                consentId: string;
                purpose: string;
                /** @enum {string} */
                status: "active" | "revoked" | "expired";
                /** Format: date-time */
                expiresAt?: string;
                /**
                 * @description Prefixed learner identifier.
                 * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                learnerId?: string;
                /**
                 * @description Prefixed ULID-style tenant operator user identifier.
                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                researcherId?: string;
            }[];
            /** @description Necessity decision summary for ethics boards (no PII). */
            necessitySummary?: {
                /**
                 * @description Prefixed blockchain-necessity decision identifier.
                 * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                necessityDecisionId?: string;
                /**
                 * @description Prefixed learning-space identifier.
                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                spaceId?: string;
                /** @enum {string} */
                outcome?: "permissioned" | "permissionless" | "no_chain";
                useBlockchain?: boolean;
                rationaleExcerpt?: string;
                /** Format: date-time */
                decidedAt?: string;
            };
            /**
             * @description Ethics-board oriented checklist for the export package contents
             *     (proofs, consent artefacts, necessity summary).
             */
            ethicsPackage?: {
                studyId?: string;
                studyTitle?: string;
                includesVerificationProofs: boolean;
                includesConsentArtefacts: boolean;
                includesNecessitySummary: boolean;
                blockCount: number;
                validVerificationCount?: number;
                noAnchorCount?: number;
                mismatchCount?: number;
                /**
                 * Format: uri
                 * @description Optional read-only share link for ethics board review.
                 */
                ethicsShareUrl?: string;
            };
            /**
             * Format: uri
             * @description Present when status is ready.
             */
            downloadUrl?: string;
            failureDetail?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            readyAt?: string;
        };
        ResearchExportListData: {
            items: {
                /**
                 * @description Prefixed research-export identifier.
                 * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                exportId: string;
                /**
                 * @description Prefixed consent-grant identifier.
                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                consentId: string;
                /**
                 * @description Prefixed learning-space identifier.
                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                spaceId?: string;
                /**
                 * @description Prefixed ULID-style tenant operator user identifier.
                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                researcherId?: string;
                /** @enum {string} */
                status: "pending" | "ready" | "failed";
                blockIds: string[];
                verificationIds: string[];
                consentArtefacts?: {
                    /**
                     * @description Prefixed consent-grant identifier.
                     * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    consentId: string;
                    purpose: string;
                    /** @enum {string} */
                    status: "active" | "revoked" | "expired";
                    /** Format: date-time */
                    expiresAt?: string;
                    /**
                     * @description Prefixed learner identifier.
                     * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    learnerId?: string;
                    /**
                     * @description Prefixed ULID-style tenant operator user identifier.
                     * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    researcherId?: string;
                }[];
                /** @description Necessity decision summary for ethics boards (no PII). */
                necessitySummary?: {
                    /**
                     * @description Prefixed blockchain-necessity decision identifier.
                     * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    necessityDecisionId?: string;
                    /**
                     * @description Prefixed learning-space identifier.
                     * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    spaceId?: string;
                    /** @enum {string} */
                    outcome?: "permissioned" | "permissionless" | "no_chain";
                    useBlockchain?: boolean;
                    rationaleExcerpt?: string;
                    /** Format: date-time */
                    decidedAt?: string;
                };
                /**
                 * @description Ethics-board oriented checklist for the export package contents
                 *     (proofs, consent artefacts, necessity summary).
                 */
                ethicsPackage?: {
                    studyId?: string;
                    studyTitle?: string;
                    includesVerificationProofs: boolean;
                    includesConsentArtefacts: boolean;
                    includesNecessitySummary: boolean;
                    blockCount: number;
                    validVerificationCount?: number;
                    noAnchorCount?: number;
                    mismatchCount?: number;
                    /**
                     * Format: uri
                     * @description Optional read-only share link for ethics board review.
                     */
                    ethicsShareUrl?: string;
                };
                /**
                 * Format: uri
                 * @description Present when status is ready.
                 */
                downloadUrl?: string;
                failureDetail?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                readyAt?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ResearchExportListResponse: {
            data: {
                items: {
                    /**
                     * @description Prefixed research-export identifier.
                     * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    exportId: string;
                    /**
                     * @description Prefixed consent-grant identifier.
                     * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    consentId: string;
                    /**
                     * @description Prefixed learning-space identifier.
                     * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    spaceId?: string;
                    /**
                     * @description Prefixed ULID-style tenant operator user identifier.
                     * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    researcherId?: string;
                    /** @enum {string} */
                    status: "pending" | "ready" | "failed";
                    blockIds: string[];
                    verificationIds: string[];
                    consentArtefacts?: {
                        /**
                         * @description Prefixed consent-grant identifier.
                         * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        consentId: string;
                        purpose: string;
                        /** @enum {string} */
                        status: "active" | "revoked" | "expired";
                        /** Format: date-time */
                        expiresAt?: string;
                        /**
                         * @description Prefixed learner identifier.
                         * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        learnerId?: string;
                        /**
                         * @description Prefixed ULID-style tenant operator user identifier.
                         * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        researcherId?: string;
                    }[];
                    /** @description Necessity decision summary for ethics boards (no PII). */
                    necessitySummary?: {
                        /**
                         * @description Prefixed blockchain-necessity decision identifier.
                         * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        necessityDecisionId?: string;
                        /**
                         * @description Prefixed learning-space identifier.
                         * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                         */
                        spaceId?: string;
                        /** @enum {string} */
                        outcome?: "permissioned" | "permissionless" | "no_chain";
                        useBlockchain?: boolean;
                        rationaleExcerpt?: string;
                        /** Format: date-time */
                        decidedAt?: string;
                    };
                    /**
                     * @description Ethics-board oriented checklist for the export package contents
                     *     (proofs, consent artefacts, necessity summary).
                     */
                    ethicsPackage?: {
                        studyId?: string;
                        studyTitle?: string;
                        includesVerificationProofs: boolean;
                        includesConsentArtefacts: boolean;
                        includesNecessitySummary: boolean;
                        blockCount: number;
                        validVerificationCount?: number;
                        noAnchorCount?: number;
                        mismatchCount?: number;
                        /**
                         * Format: uri
                         * @description Optional read-only share link for ethics board review.
                         */
                        ethicsShareUrl?: string;
                    };
                    /**
                     * Format: uri
                     * @description Present when status is ready.
                     */
                    downloadUrl?: string;
                    failureDetail?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    /** Format: date-time */
                    readyAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ResearchExportCreate: {
            /**
             * @description Prefixed consent-grant identifier.
             * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
             */
            consentId: string;
            blockIds: string[];
            /** @description Optional pre-verified ids; server re-checks before packaging. */
            verificationIds?: string[];
            studyId?: string;
            studyTitle?: string;
            /** @default false */
            allowNoAnchor: boolean;
        };
        ResearchExportResponse: {
            /** @description Verified research export package with proofs and consent artefacts. */
            data: {
                /**
                 * @description Prefixed research-export identifier.
                 * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                exportId: string;
                /**
                 * @description Prefixed consent-grant identifier.
                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                consentId: string;
                /**
                 * @description Prefixed learning-space identifier.
                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                spaceId?: string;
                /**
                 * @description Prefixed ULID-style tenant operator user identifier.
                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                 */
                researcherId?: string;
                /** @enum {string} */
                status: "pending" | "ready" | "failed";
                blockIds: string[];
                verificationIds: string[];
                consentArtefacts?: {
                    /**
                     * @description Prefixed consent-grant identifier.
                     * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    consentId: string;
                    purpose: string;
                    /** @enum {string} */
                    status: "active" | "revoked" | "expired";
                    /** Format: date-time */
                    expiresAt?: string;
                    /**
                     * @description Prefixed learner identifier.
                     * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    learnerId?: string;
                    /**
                     * @description Prefixed ULID-style tenant operator user identifier.
                     * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    researcherId?: string;
                }[];
                /** @description Necessity decision summary for ethics boards (no PII). */
                necessitySummary?: {
                    /**
                     * @description Prefixed blockchain-necessity decision identifier.
                     * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    necessityDecisionId?: string;
                    /**
                     * @description Prefixed learning-space identifier.
                     * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    spaceId?: string;
                    /** @enum {string} */
                    outcome?: "permissioned" | "permissionless" | "no_chain";
                    useBlockchain?: boolean;
                    rationaleExcerpt?: string;
                    /** Format: date-time */
                    decidedAt?: string;
                };
                /**
                 * @description Ethics-board oriented checklist for the export package contents
                 *     (proofs, consent artefacts, necessity summary).
                 */
                ethicsPackage?: {
                    studyId?: string;
                    studyTitle?: string;
                    includesVerificationProofs: boolean;
                    includesConsentArtefacts: boolean;
                    includesNecessitySummary: boolean;
                    blockCount: number;
                    validVerificationCount?: number;
                    noAnchorCount?: number;
                    mismatchCount?: number;
                    /**
                     * Format: uri
                     * @description Optional read-only share link for ethics board review.
                     */
                    ethicsShareUrl?: string;
                };
                /**
                 * Format: uri
                 * @description Present when status is ready.
                 */
                downloadUrl?: string;
                failureDetail?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                readyAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listResearchExports: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                consentId?: string;
                status?: "pending" | "ready" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exports page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /**
                                 * @description Prefixed research-export identifier.
                                 * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                exportId: string;
                                /**
                                 * @description Prefixed consent-grant identifier.
                                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                consentId: string;
                                /**
                                 * @description Prefixed learning-space identifier.
                                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                spaceId?: string;
                                /**
                                 * @description Prefixed ULID-style tenant operator user identifier.
                                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                researcherId?: string;
                                /** @enum {string} */
                                status: "pending" | "ready" | "failed";
                                blockIds: string[];
                                verificationIds: string[];
                                consentArtefacts?: {
                                    /**
                                     * @description Prefixed consent-grant identifier.
                                     * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    consentId: string;
                                    purpose: string;
                                    /** @enum {string} */
                                    status: "active" | "revoked" | "expired";
                                    /** Format: date-time */
                                    expiresAt?: string;
                                    /**
                                     * @description Prefixed learner identifier.
                                     * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    learnerId?: string;
                                    /**
                                     * @description Prefixed ULID-style tenant operator user identifier.
                                     * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    researcherId?: string;
                                }[];
                                /** @description Necessity decision summary for ethics boards (no PII). */
                                necessitySummary?: {
                                    /**
                                     * @description Prefixed blockchain-necessity decision identifier.
                                     * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    necessityDecisionId?: string;
                                    /**
                                     * @description Prefixed learning-space identifier.
                                     * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                     */
                                    spaceId?: string;
                                    /** @enum {string} */
                                    outcome?: "permissioned" | "permissionless" | "no_chain";
                                    useBlockchain?: boolean;
                                    rationaleExcerpt?: string;
                                    /** Format: date-time */
                                    decidedAt?: string;
                                };
                                /**
                                 * @description Ethics-board oriented checklist for the export package contents
                                 *     (proofs, consent artefacts, necessity summary).
                                 */
                                ethicsPackage?: {
                                    studyId?: string;
                                    studyTitle?: string;
                                    includesVerificationProofs: boolean;
                                    includesConsentArtefacts: boolean;
                                    includesNecessitySummary: boolean;
                                    blockCount: number;
                                    validVerificationCount?: number;
                                    noAnchorCount?: number;
                                    mismatchCount?: number;
                                    /**
                                     * Format: uri
                                     * @description Optional read-only share link for ethics board review.
                                     */
                                    ethicsShareUrl?: string;
                                };
                                /**
                                 * Format: uri
                                 * @description Present when status is ready.
                                 */
                                downloadUrl?: string;
                                failureDetail?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: date-time */
                                readyAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createResearchExport: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Prefixed consent-grant identifier.
                     * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                     */
                    consentId: string;
                    blockIds: string[];
                    /** @description Optional pre-verified ids; server re-checks before packaging. */
                    verificationIds?: string[];
                    studyId?: string;
                    studyTitle?: string;
                    /** @default false */
                    allowNoAnchor?: boolean;
                };
            };
        };
        responses: {
            /** @description Export created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Verified research export package with proofs and consent artefacts. */
                        data: {
                            /**
                             * @description Prefixed research-export identifier.
                             * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            exportId: string;
                            /**
                             * @description Prefixed consent-grant identifier.
                             * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            consentId: string;
                            /**
                             * @description Prefixed learning-space identifier.
                             * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            spaceId?: string;
                            /**
                             * @description Prefixed ULID-style tenant operator user identifier.
                             * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            researcherId?: string;
                            /** @enum {string} */
                            status: "pending" | "ready" | "failed";
                            blockIds: string[];
                            verificationIds: string[];
                            consentArtefacts?: {
                                /**
                                 * @description Prefixed consent-grant identifier.
                                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                consentId: string;
                                purpose: string;
                                /** @enum {string} */
                                status: "active" | "revoked" | "expired";
                                /** Format: date-time */
                                expiresAt?: string;
                                /**
                                 * @description Prefixed learner identifier.
                                 * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                learnerId?: string;
                                /**
                                 * @description Prefixed ULID-style tenant operator user identifier.
                                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                researcherId?: string;
                            }[];
                            /** @description Necessity decision summary for ethics boards (no PII). */
                            necessitySummary?: {
                                /**
                                 * @description Prefixed blockchain-necessity decision identifier.
                                 * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                necessityDecisionId?: string;
                                /**
                                 * @description Prefixed learning-space identifier.
                                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                spaceId?: string;
                                /** @enum {string} */
                                outcome?: "permissioned" | "permissionless" | "no_chain";
                                useBlockchain?: boolean;
                                rationaleExcerpt?: string;
                                /** Format: date-time */
                                decidedAt?: string;
                            };
                            /**
                             * @description Ethics-board oriented checklist for the export package contents
                             *     (proofs, consent artefacts, necessity summary).
                             */
                            ethicsPackage?: {
                                studyId?: string;
                                studyTitle?: string;
                                includesVerificationProofs: boolean;
                                includesConsentArtefacts: boolean;
                                includesNecessitySummary: boolean;
                                blockCount: number;
                                validVerificationCount?: number;
                                noAnchorCount?: number;
                                mismatchCount?: number;
                                /**
                                 * Format: uri
                                 * @description Optional read-only share link for ethics board review.
                                 */
                                ethicsShareUrl?: string;
                            };
                            /**
                             * Format: uri
                             * @description Present when status is ready.
                             */
                            downloadUrl?: string;
                            failureDetail?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            readyAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Idempotency key reuse with different body, or state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getResearchExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Verified research export package with proofs and consent artefacts. */
                        data: {
                            /**
                             * @description Prefixed research-export identifier.
                             * @example exp_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            exportId: string;
                            /**
                             * @description Prefixed consent-grant identifier.
                             * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            consentId: string;
                            /**
                             * @description Prefixed learning-space identifier.
                             * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            spaceId?: string;
                            /**
                             * @description Prefixed ULID-style tenant operator user identifier.
                             * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                             */
                            researcherId?: string;
                            /** @enum {string} */
                            status: "pending" | "ready" | "failed";
                            blockIds: string[];
                            verificationIds: string[];
                            consentArtefacts?: {
                                /**
                                 * @description Prefixed consent-grant identifier.
                                 * @example cns_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                consentId: string;
                                purpose: string;
                                /** @enum {string} */
                                status: "active" | "revoked" | "expired";
                                /** Format: date-time */
                                expiresAt?: string;
                                /**
                                 * @description Prefixed learner identifier.
                                 * @example lrn_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                learnerId?: string;
                                /**
                                 * @description Prefixed ULID-style tenant operator user identifier.
                                 * @example usr_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                researcherId?: string;
                            }[];
                            /** @description Necessity decision summary for ethics boards (no PII). */
                            necessitySummary?: {
                                /**
                                 * @description Prefixed blockchain-necessity decision identifier.
                                 * @example nec_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                necessityDecisionId?: string;
                                /**
                                 * @description Prefixed learning-space identifier.
                                 * @example spc_01HZYXK8J0M0W5N6P7Q8R9S0T1U2
                                 */
                                spaceId?: string;
                                /** @enum {string} */
                                outcome?: "permissioned" | "permissionless" | "no_chain";
                                useBlockchain?: boolean;
                                rationaleExcerpt?: string;
                                /** Format: date-time */
                                decidedAt?: string;
                            };
                            /**
                             * @description Ethics-board oriented checklist for the export package contents
                             *     (proofs, consent artefacts, necessity summary).
                             */
                            ethicsPackage?: {
                                studyId?: string;
                                studyTitle?: string;
                                includesVerificationProofs: boolean;
                                includesConsentArtefacts: boolean;
                                includesNecessitySummary: boolean;
                                blockCount: number;
                                validVerificationCount?: number;
                                noAnchorCount?: number;
                                mismatchCount?: number;
                                /**
                                 * Format: uri
                                 * @description Optional read-only share link for ethics board review.
                                 */
                                ethicsShareUrl?: string;
                            };
                            /**
                             * Format: uri
                             * @description Present when status is ready.
                             */
                            downloadUrl?: string;
                            failureDetail?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            readyAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
