/**
 * ListDeletionRequest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: blocks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDeletionRequestsParams } from "@veritrace/core/blocks";

export function createListDeletionRequestRequest(overrides: Partial<ListDeletionRequestsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
